// ─── Teacher-Only Year Quizzes (Y1–Y11) ─────────────────────────────────────
// Progressive difficulty quizzes only accessible by verified educators
'use strict';

const TEACHER_QUIZZES = [
  {
    id: 'teacher-y1',
    year: 1, title: 'Year 1 — Digital Basics',
    description: 'Introduce young learners to computers, keyboards, and staying safe online.',
    emoji: '🖥️', color: '#4ade80', difficulty: 'Foundation',
    timeLimit: 30,
    questions: [
      { question: 'What do you use to type letters on a computer?', options: ['Keyboard','Mouse','Screen','Speaker'], correct: 0, explanation: 'A keyboard has letters and numbers you press to type.' },
      { question: 'Which device lets you click on things on the screen?', options: ['Printer','Mouse','Headphones','Camera'], correct: 1, explanation: 'A mouse moves a pointer on the screen so you can click.' },
      { question: 'What should you do if a stranger messages you online?', options: ['Reply to them','Tell a grown-up','Give your name','Ignore everyone forever'], correct: 1, explanation: 'Always tell a trusted adult if a stranger contacts you online.' },
      { question: 'What does the power button do?', options: ['Makes it louder','Turns it on or off','Opens a game','Prints a page'], correct: 1, explanation: 'The power button turns your computer on and off.' },
      { question: 'Which one is an input device?', options: ['Monitor','Printer','Keyboard','Speaker'], correct: 2, explanation: 'A keyboard is an input device — you put information IN.' },
      { question: 'What do we call pictures on a computer screen you can click?', options: ['Icons','Stickers','Photos','Drawings'], correct: 0, explanation: 'Icons are small pictures that open programs when clicked.' },
      { question: 'Is it safe to share your password with friends?', options: ['Yes, always','Only best friends','No, never','Only at school'], correct: 2, explanation: 'Never share your password — keep it secret and safe.' },
      { question: 'What does a printer do?', options: ['Plays music','Makes paper copies','Stores files','Takes photos'], correct: 1, explanation: 'A printer puts what\'s on screen onto paper.' },
      { question: 'Which is a way to stay safe online?', options: ['Click every link','Share your address','Ask a grown-up for help','Download everything'], correct: 2, explanation: 'When unsure online, ask a trusted adult for help.' },
      { question: 'What shape is the "Enter" key usually?', options: ['Circle','Triangle','Rectangle with arrow','Star'], correct: 2, explanation: 'The Enter key is usually a rectangle shape, sometimes with a bent arrow.' },
    ],
  },
  {
    id: 'teacher-y2',
    year: 2, title: 'Year 2 — Computer Explorers',
    description: 'Learn about files, folders, and simple instructions computers follow.',
    emoji: '📁', color: '#38bdf8', difficulty: 'Foundation',
    timeLimit: 28,
    questions: [
      { question: 'Where do computers store your work?', options: ['In the mouse','In files and folders','In the keyboard','In the screen'], correct: 1, explanation: 'Computers save your work in files, organized into folders.' },
      { question: 'What is an algorithm?', options: ['A type of computer','A set of step-by-step instructions','A kind of cable','A computer game'], correct: 1, explanation: 'An algorithm is a set of clear steps to solve a problem or do a task.' },
      { question: 'Which of these is software?', options: ['Monitor','A word processor','USB cable','Keyboard'], correct: 1, explanation: 'Software is programs that run ON a computer, like a word processor.' },
      { question: 'What does "save" do to your work?', options: ['Deletes it','Prints it','Keeps it stored safely','Sends it to someone'], correct: 2, explanation: 'Saving stores your work so you can open it again later.' },
      { question: 'What is the Internet?', options: ['A single computer','A network connecting millions of computers','A type of keyboard','A programming language'], correct: 1, explanation: 'The Internet is a huge network that connects computers worldwide.' },
      { question: 'Which device takes photos for the computer?', options: ['Microphone','Webcam','Printer','Hard drive'], correct: 1, explanation: 'A webcam captures pictures and video for your computer.' },
      { question: 'What happens when you "undo" something?', options: ['It saves your work','It goes back one step','It closes the program','It prints the page'], correct: 1, explanation: 'Undo reverses the last thing you did — like a time machine for one step!' },
      { question: 'In a set of instructions, what must each step be?', options: ['Long and detailed','Clear and in order','Funny and silly','Written in code'], correct: 1, explanation: 'Good instructions are clear and in the right order.' },
      { question: 'What is a "bug" in computing?', options: ['An actual insect','A mistake in a program','A computer virus','A broken screen'], correct: 1, explanation: 'A bug is a mistake or error that makes a program not work properly.' },
      { question: 'Which one stores information even when the computer is off?', options: ['RAM','Hard drive / SSD','Screen','CPU'], correct: 1, explanation: 'Hard drives and SSDs keep your files even when the power is off.' },
    ],
  },
  {
    id: 'teacher-y3',
    year: 3, title: 'Year 3 — Coding Foundations',
    description: 'Sequences, loops, and simple debugging concepts for young coders.',
    emoji: '🔄', color: '#a78bfa', difficulty: 'Developing',
    timeLimit: 25,
    questions: [
      { question: 'What is a "loop" in programming?', options: ['A type of error','An instruction that repeats','A way to delete code','A computer screen shape'], correct: 1, explanation: 'A loop repeats a set of instructions multiple times.' },
      { question: 'In Scratch, which block makes a character move?', options: ['Say block','Move 10 steps','When clicked','Forever block'], correct: 1, explanation: 'The "move 10 steps" block makes a sprite move forward.' },
      { question: 'What is "debugging"?', options: ['Adding more code','Finding and fixing mistakes','Making code run faster','Deleting a program'], correct: 1, explanation: 'Debugging means finding errors (bugs) and fixing them.' },
      { question: 'What does a "sequence" mean in coding?', options: ['Random instructions','Instructions in a specific order','A type of variable','A loop that never ends'], correct: 1, explanation: 'A sequence is instructions that run one after another in order.' },
      { question: 'What is a "variable" in simple terms?', options: ['A fixed number','A box that stores information','A type of loop','A computer part'], correct: 1, explanation: 'A variable is like a labelled box that holds a value which can change.' },
      { question: 'What will "Repeat 3: Move, Turn" do?', options: ['Move once','Move and turn 3 times','Turn 3 times only','Nothing'], correct: 1, explanation: 'It repeats "move then turn" three times.' },
      { question: 'Which is an example of an "input"?', options: ['Sound from speakers','Text on screen','Clicking a mouse button','A printed document'], correct: 2, explanation: 'Input is information going INTO the computer, like a mouse click.' },
      { question: 'What is an "output"?', options: ['Typing on keyboard','Moving the mouse','Sound from speakers','Plugging in a USB'], correct: 2, explanation: 'Output is information coming OUT of the computer, like sound.' },
      { question: 'In Scratch, what does the "if" block do?', options: ['Always runs the code inside','Runs code only when a condition is true','Repeats code forever','Stops the program'], correct: 1, explanation: 'An "if" block checks a condition and only runs when it\'s true.' },
      { question: 'Why is the ORDER of instructions important?', options: ['It doesn\'t matter','Different orders give different results','Computers ignore order','Only the first instruction matters'], correct: 1, explanation: 'The order matters because changing it changes what happens!' },
    ],
  },
  {
    id: 'teacher-y4',
    year: 4, title: 'Year 4 — Networks & Data',
    description: 'How the internet works, data representation, and digital literacy.',
    emoji: '🌐', color: '#f472b6', difficulty: 'Developing',
    timeLimit: 25,
    questions: [
      { question: 'What does "HTML" stand for?', options: ['How To Make Links','HyperText Markup Language','High Tech Modern Language','Home Tool Management Layer'], correct: 1, explanation: 'HTML = HyperText Markup Language — the code behind web pages.' },
      { question: 'What does a "router" do?', options: ['Stores files','Directs internet traffic between devices','Displays web pages','Creates passwords'], correct: 1, explanation: 'A router directs data between your devices and the internet.' },
      { question: 'What is binary?', options: ['A type of virus','A number system using only 0 and 1','A programming language','A computer brand'], correct: 1, explanation: 'Binary uses just 0s and 1s — it\'s how computers store all data.' },
      { question: 'What does "URL" stand for?', options: ['Universal Reset Link','Uniform Resource Locator','United Router Location','Under Rated Language'], correct: 1, explanation: 'A URL is the address of a web page, like its location on the internet.' },
      { question: 'What is a "search engine"?', options: ['A part of a car','A tool to find things on the internet','A type of code','A computer hardware part'], correct: 1, explanation: 'A search engine like Google helps you find information online.' },
      { question: 'How do computers store images?', options: ['As drawings','As tiny coloured dots called pixels','As text files','As sound waves'], correct: 1, explanation: 'Images are made of thousands of tiny dots (pixels), each with a colour value.' },
      { question: 'What is a "network"?', options: ['One computer alone','Two or more connected computers','A type of software','A wireless keyboard'], correct: 1, explanation: 'A network is computers linked together to share data.' },
      { question: 'What is "copyright"?', options: ['Copying someone\'s work freely','Legal protection for creators\' work','A type of font','A coding command'], correct: 1, explanation: 'Copyright protects creators — you need permission to use their work.' },
      { question: 'The number 5 in binary is:', options: ['100','110','101','111'], correct: 2, explanation: '5 in binary is 101: (1×4) + (0×2) + (1×1) = 5' },
      { question: 'What is "bandwidth"?', options: ['The width of a monitor','How much data can be sent at once','A type of cable','A music term'], correct: 1, explanation: 'Bandwidth measures how much data your connection can handle at once.' },
    ],
  },
  {
    id: 'teacher-y5',
    year: 5, title: 'Year 5 — Algorithms & Logic',
    description: 'Selection, iteration, boolean logic, and computational thinking.',
    emoji: '🧮', color: '#fb923c', difficulty: 'Intermediate',
    timeLimit: 22,
    questions: [
      { question: 'What is "selection" in programming?', options: ['Choosing random code','Making decisions with IF statements','Selecting text','Picking a programming language'], correct: 1, explanation: 'Selection means the program chooses what to do based on a condition.' },
      { question: 'What does "iteration" mean?', options: ['Stopping a program','Repeating code (loops)','Writing new code','Testing code'], correct: 1, explanation: 'Iteration means repeating — loops are iteration in action.' },
      { question: 'What is a "boolean" value?', options: ['A decimal number','True or False','A text string','A list of items'], correct: 1, explanation: 'Boolean values are either TRUE or FALSE — nothing else.' },
      { question: 'What does the operator AND do?', options: ['True if either is true','True only if BOTH are true','Always true','Reverses the value'], correct: 1, explanation: 'AND requires both conditions to be true: True AND True = True.' },
      { question: 'What is "decomposition"?', options: ['Deleting code','Breaking a big problem into smaller parts','Making code longer','A type of bug'], correct: 1, explanation: 'Decomposition = breaking complex problems into manageable pieces.' },
      { question: 'What is "abstraction"?', options: ['Making things more complicated','Removing unnecessary detail','Abstract art on screen','A type of data'], correct: 1, explanation: 'Abstraction means focusing on what matters and hiding complexity.' },
      { question: 'What does "NOT True" equal?', options: ['True','False','Null','Error'], correct: 1, explanation: 'NOT flips the value: NOT True = False.' },
      { question: 'In a flowchart, what shape represents a decision?', options: ['Rectangle','Diamond','Circle','Arrow'], correct: 1, explanation: 'Diamonds represent decision points (yes/no questions) in flowcharts.' },
      { question: 'What is "pattern recognition"?', options: ['Drawing patterns','Spotting similarities in problems','A display setting','A type of loop'], correct: 1, explanation: 'Pattern recognition means finding similarities that help solve problems.' },
      { question: 'Which loop runs a set number of times?', options: ['While loop','For loop','Infinite loop','Do loop'], correct: 1, explanation: 'A for loop runs a specific number of times: "for i = 1 to 10".' },
    ],
  },
  {
    id: 'teacher-y6',
    year: 6, title: 'Year 6 — Web & Cyber Security',
    description: 'Web development basics, online safety, encryption, and responsible tech use.',
    emoji: '🔒', color: '#ef4444', difficulty: 'Intermediate',
    timeLimit: 22,
    questions: [
      { question: 'What does "phishing" mean?', options: ['Going fishing online','Tricking people into revealing personal information','A type of game','Sending fish emojis'], correct: 1, explanation: 'Phishing = fake messages designed to steal your personal data.' },
      { question: 'What is "encryption"?', options: ['Deleting data','Scrambling data so only authorised people can read it','Compressing files','A programming language'], correct: 1, explanation: 'Encryption scrambles information into a code for security.' },
      { question: 'What does CSS do for a website?', options: ['Adds logic','Controls styling and layout','Stores data','Creates animations only'], correct: 1, explanation: 'CSS (Cascading Style Sheets) controls how a website looks.' },
      { question: 'What is "two-factor authentication"?', options: ['Two passwords','Verifying identity with two different methods','Two usernames','Logging in twice'], correct: 1, explanation: '2FA uses two methods (like password + phone code) for extra security.' },
      { question: 'What is a "cookie" on the internet?', options: ['A snack','A small file that stores website preferences','A virus','A bookmark'], correct: 1, explanation: 'Cookies store small pieces of data about your visit to a website.' },
      { question: 'What does "HTTPS" mean compared to HTTP?', options: ['It\'s faster','It\'s encrypted and secure','It\'s newer','It has more pages'], correct: 1, explanation: 'HTTPS adds encryption — the "S" stands for Secure.' },
      { question: 'What is "malware"?', options: ['Good software','Software designed to harm or exploit','A male programmer','A type of hardware'], correct: 1, explanation: 'Malware = malicious software: viruses, trojans, ransomware, etc.' },
      { question: 'What is a "firewall"?', options: ['A wall on fire','A security system that monitors network traffic','A type of router','A coding language'], correct: 1, explanation: 'A firewall monitors and controls incoming/outgoing network traffic.' },
      { question: 'What is the "digital footprint"?', options: ['A fingerprint scanner','The trail of data you leave online','A type of file','A virtual shoe'], correct: 1, explanation: 'Your digital footprint is all the data traces you leave when using the internet.' },
      { question: 'What is "open source" software?', options: ['Software you buy','Software whose code anyone can view and modify','Broken software','Software without a name'], correct: 1, explanation: 'Open source means the code is publicly available for anyone to use and improve.' },
    ],
  },
  {
    id: 'teacher-y7',
    year: 7, title: 'Year 7 — Programming Principles',
    description: 'Variables, data types, conditionals, and real Python/JS syntax.',
    emoji: '🐍', color: '#3b82f6', difficulty: 'Secure',
    timeLimit: 20,
    questions: [
      { question: 'In Python, what does print("Hello") do?', options: ['Saves "Hello" to a file','Displays "Hello" on screen','Creates a variable','Deletes the word Hello'], correct: 1, explanation: 'print() outputs text to the screen — it\'s the most basic output command.' },
      { question: 'What data type is the value 3.14?', options: ['Integer','String','Float','Boolean'], correct: 2, explanation: '3.14 has a decimal point, making it a float (floating-point number).' },
      { question: 'What does x = x + 1 do?', options: ['Sets x to 1','Increases x by 1','Creates an error','Compares x to 1'], correct: 1, explanation: 'It takes the current value of x, adds 1, and stores the result back in x.' },
      { question: 'What is a "string"?', options: ['A number','Text data enclosed in quotes','A boolean','A list'], correct: 1, explanation: 'A string is text — characters between quotes like "Hello World".' },
      { question: 'What will "5" + "3" give in JavaScript?', options: ['8','53','Error','15'], correct: 1, explanation: 'When both are strings, + concatenates: "5" + "3" = "53".' },
      { question: 'What is an "array" (or list)?', options: ['A single value','A collection of values in order','A function','A boolean'], correct: 1, explanation: 'An array/list stores multiple values in a single variable.' },
      { question: 'What does == check for?', options: ['Assignment','Equality (are two values the same?)','Greater than','Addition'], correct: 1, explanation: '== checks if two values are equal. Different from = which assigns.' },
      { question: 'What is a "function"?', options: ['A variable type','A reusable block of code','A loop','A data file'], correct: 1, explanation: 'Functions are reusable code blocks you can call by name.' },
      { question: 'What happens if you divide by zero?', options: ['Returns 0','Causes an error','Returns infinity','Returns 1'], correct: 1, explanation: 'Dividing by zero causes an error in most programming languages.' },
      { question: 'What is "pseudocode"?', options: ['Real Python code','Plain-language description of an algorithm','A broken program','A type of encryption'], correct: 1, explanation: 'Pseudocode describes logic in plain language before writing actual code.' },
    ],
  },
  {
    id: 'teacher-y8',
    year: 8, title: 'Year 8 — Data & Systems',
    description: 'Databases, binary arithmetic, hardware architecture, and operating systems.',
    emoji: '💾', color: '#8b5cf6', difficulty: 'Secure',
    timeLimit: 20,
    questions: [
      { question: 'What is a "database"?', options: ['A spreadsheet','An organised collection of structured data','A web browser','A type of code'], correct: 1, explanation: 'A database stores and organises large amounts of data efficiently.' },
      { question: 'What does "SQL" stand for?', options: ['Simple Question Language','Structured Query Language','System Quality Level','Standard Quick Lookup'], correct: 1, explanation: 'SQL = Structured Query Language — used to manage databases.' },
      { question: 'What is the binary value of decimal 10?', options: ['1010','1100','1001','1110'], correct: 0, explanation: '10 in binary: 8+2 = 1010 (8,4,2,1 → 1,0,1,0).' },
      { question: 'What is the CPU?', options: ['A storage device','The central processing unit — the brain','A display unit','A network card'], correct: 1, explanation: 'The CPU processes instructions — it\'s the "brain" of the computer.' },
      { question: 'What is RAM used for?', options: ['Long-term storage','Temporary fast memory for running programs','Connecting to WiFi','Displaying graphics'], correct: 1, explanation: 'RAM holds data for programs currently running — it\'s fast but temporary.' },
      { question: 'What is an "operating system"?', options: ['An app','Software that manages hardware and software resources','A type of CPU','A network'], correct: 1, explanation: 'The OS (Windows, macOS, Linux) manages everything on your computer.' },
      { question: 'How many bits are in a byte?', options: ['4','8','16','32'], correct: 1, explanation: '1 byte = 8 bits. A bit is a single 0 or 1.' },
      { question: 'What does "SELECT * FROM students" do in SQL?', options: ['Deletes all students','Gets all data from the students table','Creates a new table','Updates a student'], correct: 1, explanation: 'SELECT * FROM students retrieves all records from the students table.' },
      { question: 'What is "cloud computing"?', options: ['Computing in the sky','Using remote servers over the internet','A weather app','A type of hard drive'], correct: 1, explanation: 'Cloud computing uses remote servers accessed via the internet.' },
      { question: 'What is "hexadecimal"?', options: ['Base-2','Base-10','Base-16','Base-8'], correct: 2, explanation: 'Hex is base-16, using digits 0-9 and letters A-F. Common for colours.' },
    ],
  },
  {
    id: 'teacher-y9',
    year: 9, title: 'Year 9 — Advanced Programming',
    description: 'OOP concepts, file handling, error handling, and algorithm efficiency.',
    emoji: '⚙️', color: '#06b6d4', difficulty: 'Advanced',
    timeLimit: 18,
    questions: [
      { question: 'What is "Object-Oriented Programming"?', options: ['Programming with numbers','Programming using objects that combine data and methods','A visual programming language','Programming without variables'], correct: 1, explanation: 'OOP organises code into objects — bundles of data (properties) and actions (methods).' },
      { question: 'What is "inheritance" in OOP?', options: ['Copying a file','A class receiving properties/methods from a parent class','A type of loop','Deleting old code'], correct: 1, explanation: 'Inheritance lets a class "inherit" features from another class.' },
      { question: 'What is a "try-catch" block used for?', options: ['Catching bugs at compile time','Handling errors gracefully at runtime','Trying new languages','Testing performance'], correct: 1, explanation: 'Try-catch lets your program handle errors without crashing.' },
      { question: 'What is "Big O notation" used for?', options: ['Grading code','Describing algorithm efficiency/speed','A programming language','File sizes'], correct: 1, explanation: 'Big O describes how an algorithm\'s time/space scales with input size.' },
      { question: 'What is O(n) time complexity?', options: ['Constant time','Linear — grows proportionally with input','Quadratic','Logarithmic'], correct: 1, explanation: 'O(n) means the time grows linearly: double the input, double the time.' },
      { question: 'What is a "class" in OOP?', options: ['A school class','A blueprint for creating objects','A type of variable','A function'], correct: 1, explanation: 'A class is a template that defines what an object will look like and do.' },
      { question: 'What does "encapsulation" mean?', options: ['Making code public','Hiding internal details and exposing only what\'s needed','Encrypting data','Compressing files'], correct: 1, explanation: 'Encapsulation hides an object\'s internal workings, showing only an interface.' },
      { question: 'What is "recursion"?', options: ['A loop','A function that calls itself','An error','A data type'], correct: 1, explanation: 'Recursion is when a function calls itself to solve smaller sub-problems.' },
      { question: 'What is a "stack overflow"?', options: ['Too much data in a database','When recursion goes too deep, filling the call stack','A website','When RAM is full'], correct: 1, explanation: 'A stack overflow happens when too many function calls pile up.' },
      { question: 'What is "polymorphism"?', options: ['Multiple variables','Objects of different classes responding to the same method call','A data structure','A network protocol'], correct: 1, explanation: 'Polymorphism = same method name, different behaviour depending on the object.' },
    ],
  },
  {
    id: 'teacher-y10',
    year: 10, title: 'Year 10 — GCSE Computer Science',
    description: 'Exam-level: logic gates, sorting algorithms, data representation, and ethics.',
    emoji: '📐', color: '#eab308', difficulty: 'Advanced',
    timeLimit: 18,
    questions: [
      { question: 'What is the output of AND gate when inputs are 1 and 0?', options: ['1','0','Undefined','Error'], correct: 1, explanation: 'AND gate: both inputs must be 1 for output 1. 1 AND 0 = 0.' },
      { question: 'What is the time complexity of bubble sort (worst case)?', options: ['O(n)','O(n log n)','O(n²)','O(1)'], correct: 2, explanation: 'Bubble sort compares every pair — worst case is O(n²).' },
      { question: 'What does an OR gate output when both inputs are 0?', options: ['1','0','Error','Undefined'], correct: 1, explanation: 'OR gate: at least one input must be 1 for output 1. 0 OR 0 = 0.' },
      { question: 'How many unique values can 8 bits represent?', options: ['8','128','256','512'], correct: 2, explanation: '2⁸ = 256 unique values (0 to 255).' },
      { question: 'What is "normalisation" in databases?', options: ['Making data normal','Organising data to reduce redundancy','Sorting alphabetically','Encrypting data'], correct: 1, explanation: 'Normalisation structures databases to minimise data duplication.' },
      { question: 'Which sorting algorithm uses "divide and conquer"?', options: ['Bubble sort','Insertion sort','Merge sort','Selection sort'], correct: 2, explanation: 'Merge sort splits the list in half recursively, then merges sorted halves.' },
      { question: 'What is "lossy" compression?', options: ['Compression with no data loss','Compression that permanently removes some data','A broken file','An encryption method'], correct: 1, explanation: 'Lossy compression (like JPEG) permanently removes data to reduce file size.' },
      { question: 'What is a "logic gate"?', options: ['A physical gate','An electronic circuit performing a boolean function','A software firewall','A type of cable'], correct: 1, explanation: 'Logic gates are circuits that implement boolean operations (AND, OR, NOT, etc.).' },
      { question: 'What is "fetch-decode-execute"?', options: ['A dance move','The CPU cycle for processing instructions','A file transfer protocol','A debugging method'], correct: 1, explanation: 'The CPU cycle: fetch instruction from memory, decode it, execute it. Repeat.' },
      { question: 'What is an "ethical issue" in computing?', options: ['A coding error','A question about right and wrong in technology use','A hardware problem','A software update'], correct: 1, explanation: 'Ethical issues include privacy, AI bias, surveillance, digital divide, and more.' },
    ],
  },
  {
    id: 'teacher-y11',
    year: 11, title: 'Year 11 — Exam Mastery',
    description: 'Final-year challenge: networking protocols, advanced algorithms, and theory.',
    emoji: '🎓', color: '#dc2626', difficulty: 'Expert',
    timeLimit: 15,
    questions: [
      { question: 'What layer of the TCP/IP model handles routing?', options: ['Application','Transport','Internet (Network)','Link'], correct: 2, explanation: 'The Internet layer (IP) handles addressing and routing packets.' },
      { question: 'What is the worst-case complexity of binary search?', options: ['O(n)','O(n²)','O(log n)','O(1)'], correct: 2, explanation: 'Binary search halves the search space each step: O(log n).' },
      { question: 'What is "Dijkstra\'s algorithm" used for?', options: ['Sorting data','Finding shortest path in a weighted graph','Encrypting data','Compressing files'], correct: 1, explanation: 'Dijkstra\'s finds the shortest path between nodes in a weighted graph.' },
      { question: 'What does TCP guarantee that UDP does not?', options: ['Speed','Reliable, ordered delivery of data','Encryption','Compression'], correct: 1, explanation: 'TCP guarantees packets arrive correctly and in order. UDP is faster but unreliable.' },
      { question: 'In a binary tree, what is an "in-order traversal"?', options: ['Root, Left, Right','Left, Root, Right','Left, Right, Root','Right, Root, Left'], correct: 1, explanation: 'In-order: visit left subtree, then root, then right subtree.' },
      { question: 'What is "hashing" used for?', options: ['Sorting data','Mapping data to a fixed-size value for fast lookup','Drawing graphics','Network routing'], correct: 1, explanation: 'Hashing converts data into a fixed-size hash — used in hash tables and security.' },
      { question: 'What is the difference between "compiler" and "interpreter"?', options: ['No difference','Compiler translates all at once; interpreter line-by-line','Compiler is slower','Interpreter is for hardware'], correct: 1, explanation: 'A compiler translates the entire program before running; an interpreter does it line by line.' },
      { question: 'What does "ACID" stand for in databases?', options: ['Atomicity, Consistency, Isolation, Durability','Advanced Computing Interface Design','Automated Compiled Indexed Data','None of these'], correct: 0, explanation: 'ACID ensures reliable database transactions: Atomicity, Consistency, Isolation, Durability.' },
      { question: 'What is "virtual memory"?', options: ['Cloud storage','Using hard drive space as extra RAM','Imaginary memory','Memory in a virtual machine only'], correct: 1, explanation: 'Virtual memory uses disk space to extend RAM when physical memory is full.' },
      { question: 'What is the "halting problem"?', options: ['Stopping a loop','The proven impossibility of determining if any program will finish','A CPU error','A network timeout'], correct: 1, explanation: 'Alan Turing proved no algorithm can determine if every program will eventually halt.' },
    ],
  },
  // ── Year 12 — A-Level Foundation ─────────────────────────────────────────
  {
    id: 'teacher-y12',
    year: 12, title: 'Year 12 — A-Level Foundation',
    description: 'A-Level entry: object-oriented programming, Boolean algebra, and computational thinking.',
    emoji: '🧩', color: '#6366f1', difficulty: 'Advanced',
    timeLimit: 18,
    questions: [
      { question: 'What is polymorphism in OOP?', options: ['Many objects in memory','One interface, many implementations','A type of loop','Deleting objects'], correct: 1, explanation: 'Polymorphism lets subclasses provide their own implementation of a parent method.' },
      { question: 'What does DeMorgan\'s Law state?', options: ['NOT(A AND B) = NOT A OR NOT B','A AND B = A OR B','NOT A = A','A OR B = A AND B'], correct: 0, explanation: 'DeMorgan\'s: NOT(A AND B) ≡ NOT A OR NOT B, and NOT(A OR B) ≡ NOT A AND NOT B.' },
      { question: 'What is a "stack overflow"?', options: ['Too much data on the heap','Recursion exceeding the call stack limit','A network error','Corrupt RAM'], correct: 1, explanation: 'If recursion never terminates, the call stack grows until it overflows.' },
      { question: 'In Big O notation, what is O(n log n)?', options: ['Constant','Quadratic','Linearithmic — typical of efficient sorts','Exponential'], correct: 2, explanation: 'O(n log n) is linearithmic — seen in merge sort and heap sort.' },
      { question: 'What is the purpose of an abstract class?', options: ['It cannot be instantiated; it defines structure for subclasses','It stores global variables','It replaces interfaces','It compresses data'], correct: 0, explanation: 'Abstract classes provide a blueprint — subclasses must implement abstract methods.' },
      { question: 'What is a "race condition"?', options: ['Sorting algorithms competing','Two threads accessing shared data simultaneously causing unpredictable results','A CPU benchmark','Fast network access'], correct: 1, explanation: 'Race conditions occur when threads access/modify shared state without synchronisation.' },
      { question: 'What does "encapsulation" mean in OOP?', options: ['Encrypting code','Bundling data and methods, hiding internal state','Inheriting from a parent','Overloading operators'], correct: 1, explanation: 'Encapsulation hides implementation details; data is accessed via public methods only.' },
      { question: 'What is a "semaphore" used for?', options: ['Network signalling','Controlling access to shared resources in concurrent programming','Sorting','Rendering graphics'], correct: 1, explanation: 'Semaphores are synchronisation tools that control how many threads access a resource.' },
      { question: 'Convert 0.625 to binary fraction.', options: ['0.101','0.011','0.110','0.111'], correct: 0, explanation: '0.625 × 2 = 1.25 → 1; 0.25 × 2 = 0.5 → 0; 0.5 × 2 = 1.0 → 1. Answer: 0.101' },
      { question: 'What is "memoisation"?', options: ['Writing code comments','Caching function results to avoid re-computation','A type of encryption','Garbage collection'], correct: 1, explanation: 'Memoisation stores previously computed results to speed up recursive algorithms.' },
    ],
  },
  // ── Year 13 — A-Level Mastery ─────────────────────────────────────────────
  {
    id: 'teacher-y13',
    year: 13, title: 'Year 13 — A-Level Mastery',
    description: 'Top-level A2: functional programming, complexity theory, AI, and hardware architecture.',
    emoji: '🏆', color: '#f43f5e', difficulty: 'Expert',
    timeLimit: 15,
    questions: [
      { question: 'What is a "Turing Complete" language?', options: ['Any language with loops','A language that can simulate any Turing machine','A language with no bugs','A compiled language'], correct: 1, explanation: 'A Turing Complete language can compute anything a Turing machine can, given enough time/memory.' },
      { question: 'What is a "monad" in functional programming?', options: ['A single function','A design pattern for handling side effects in a pure way','A recursive loop','A hardware interrupt'], correct: 1, explanation: 'Monads chain operations handling values in context (e.g. Maybe, IO) without side effects.' },
      { question: 'What is P vs NP?', options: ['Python vs Node.js','The unsolved question of whether every efficiently verifiable problem is efficiently solvable','A sorting benchmark','Hardware vs software performance'], correct: 1, explanation: 'P=problems solvable in polynomial time; NP=verifiable in polynomial time. Are they equal? Unknown.' },
      { question: 'What is "lazy evaluation"?', options: ['Slow code','Delaying evaluation of an expression until its value is needed','Garbage collection','A compiler optimisation only'], correct: 1, explanation: 'Lazy evaluation (Haskell) defers computation until needed, enabling infinite data structures.' },
      { question: 'In neural networks, what is "backpropagation"?', options: ['Forward data pass','Algorithm computing gradients by propagating errors backward to update weights','Storing training data','Normalising inputs'], correct: 1, explanation: 'Backpropagation calculates the gradient of the loss function w.r.t. each weight for training.' },
      { question: 'What is a "Von Neumann bottleneck"?', options: ['Slow internet','The speed mismatch between CPU and memory causing a performance limit','An OS scheduling issue','Overheating'], correct: 1, explanation: 'CPU and memory share a single bus; the CPU waits for data, creating a throughput bottleneck.' },
      { question: 'What distinguishes RISC from CISC architecture?', options: ['RISC has more instructions','RISC uses fewer, simpler instructions executed in one clock cycle; CISC uses complex multi-cycle instructions','No difference','CISC is faster'], correct: 1, explanation: 'RISC (ARM) = simple instructions, fast pipelines. CISC (x86) = complex instructions, more compact code.' },
      { question: 'What is "deadlock" in concurrent systems?', options: ['A slow thread','Two or more threads permanently blocked waiting for each other\'s locked resources','A crashed server','A compile error'], correct: 1, explanation: 'Deadlock: Thread A holds Resource 1 waiting for Resource 2; Thread B holds Resource 2 waiting for Resource 1. Neither proceeds.' },
      { question: 'What is a "regular language"?', options: ['A well-written language','A language describable by a finite automaton or regular expression','Any modern language','A language without bugs'], correct: 1, explanation: 'Regular languages are the simplest class in the Chomsky hierarchy — accepted by finite automata.' },
      { question: 'What does "gradient descent" minimise?', options: ['Memory usage','A loss/cost function to improve model accuracy','Network latency','CPU cycles'], correct: 1, explanation: 'Gradient descent iteratively moves in the direction of steepest loss decrease to find a minimum.' },
    ],
  },
];

// ── 5 Cross-Curriculum Quizzes per Year Group (Y1–Y13) ───────────────────────
// Topics: Science, History, Math, Literacy, Coding — vary by year
const CURRICULUM_QUIZZES = [
  // Y1
  { id:'curr-y1-science',  year:1, subject:'Science',  title:'Y1 Science: Living Things', emoji:'🌱', color:'#22c55e', difficulty:'Foundation', timeLimit:30,
    questions:[
      {question:'What do plants need to grow?',options:['Water & sunlight','Just water','Only soil','Just light'],correct:0,explanation:'Plants need sunlight, water, and nutrients from soil.'},
      {question:'Which animal lays eggs?',options:['Dog','Cat','Bird','Cow'],correct:2,explanation:'Birds lay eggs. Most mammals give birth to live young.'},
      {question:'What body part do we use to breathe?',options:['Heart','Lungs','Stomach','Brain'],correct:1,explanation:'Lungs take in oxygen and release carbon dioxide.'},
      {question:'Which is a fruit?',options:['Carrot','Potato','Apple','Onion'],correct:2,explanation:'An apple is a fruit — it grows from a flower and contains seeds.'},
      {question:'What does a caterpillar turn into?',options:['Ladybird','Butterfly','Bee','Moth — always'],correct:1,explanation:'Caterpillars metamorphose into butterflies or moths!'},
    ]},
  { id:'curr-y1-history', year:1, subject:'History', title:'Y1 History: Famous People', emoji:'👑', color:'#f59e0b', difficulty:'Foundation', timeLimit:30,
    questions:[
      {question:'What was Florence Nightingale famous for?',options:['Flying','Nursing sick soldiers','Building bridges','Writing stories'],correct:1,explanation:'Florence Nightingale revolutionised nursing and hospital hygiene.'},
      {question:'Neil Armstrong was the first person to walk on…?',options:['Mars','The Moon','Jupiter','Venus'],correct:1,explanation:'Neil Armstrong walked on the Moon in 1969 during Apollo 11.'},
      {question:'Which queen ruled England for 63 years in the 1800s?',options:['Queen Mary','Queen Victoria','Queen Elizabeth I','Queen Anne'],correct:1,explanation:'Queen Victoria reigned from 1837–1901, one of the longest reigns ever.'},
      {question:'Rosa Parks was famous for standing up for…?',options:['Animal rights','Workers\' pay','Civil rights and racial equality','Environmental issues'],correct:2,explanation:'Rosa Parks refused to give up her bus seat in 1955, sparking the civil rights movement.'},
      {question:'What did Amelia Earhart do first?',options:['Climb Everest','Swim the Channel','Fly solo across the Atlantic Ocean','Sail around the world'],correct:2,explanation:'Amelia Earhart became the first woman to fly solo across the Atlantic in 1932.'},
    ]},
  { id:'curr-y1-maths', year:1, subject:'Maths', title:'Y1 Maths: Numbers & Shapes', emoji:'🔢', color:'#3b82f6', difficulty:'Foundation', timeLimit:30,
    questions:[
      {question:'What is 3 + 4?',options:['6','7','8','5'],correct:1,explanation:'3 + 4 = 7.'},
      {question:'How many sides does a triangle have?',options:['2','4','3','5'],correct:2,explanation:'A triangle always has exactly 3 sides.'},
      {question:'What comes after 9?',options:['8','11','10','12'],correct:2,explanation:'10 comes after 9.'},
      {question:'What is 10 − 3?',options:['6','8','7','9'],correct:2,explanation:'10 − 3 = 7.'},
      {question:'Which number is the biggest?',options:['12','9','15','11'],correct:2,explanation:'15 is the largest of these numbers.'},
    ]},
  { id:'curr-y1-literacy', year:1, subject:'Literacy', title:'Y1 Literacy: Phonics & Words', emoji:'📚', color:'#ec4899', difficulty:'Foundation', timeLimit:30,
    questions:[
      {question:'Which word rhymes with "cat"?',options:['Cup','Hat','Sit','Dog'],correct:1,explanation:'"Hat" rhymes with "cat" — both end in the "-at" sound.'},
      {question:'What is the first letter of "elephant"?',options:['A','F','E','I'],correct:2,explanation:'"Elephant" starts with the letter E.'},
      {question:'Which sentence uses a capital letter correctly?',options:['the dog ran.','The dog ran.','the Dog ran.','the dog Ran.'],correct:1,explanation:'Sentences begin with a capital letter.'},
      {question:'What is a "noun"?',options:['A doing word','A describing word','A naming word','A connecting word'],correct:2,explanation:'A noun is a naming word — person, place, or thing.'},
      {question:'Which word has a silent letter?',options:['Cat','Know','Run','Big'],correct:1,explanation:'"Know" has a silent K — we say "no".'},
    ]},
  { id:'curr-y1-coding', year:1, subject:'Coding', title:'Y1 Coding: Sequences', emoji:'💻', color:'#8b5cf6', difficulty:'Foundation', timeLimit:30,
    questions:[
      {question:'In Scratch, what does "move 10 steps" do?',options:['Turns the sprite','Moves sprite forward 10 steps','Stops the sprite','Changes colour'],correct:1,explanation:'The move block makes your sprite travel forward by that many steps.'},
      {question:'What is an "algorithm"?',options:['A computer game','Step-by-step instructions to solve a problem','A type of robot','A kind of bug'],correct:1,explanation:'An algorithm is a clear set of steps — like a recipe for computers!'},
      {question:'Which block starts a Scratch program?',options:['Stop all','When Green Flag clicked','Move 10 steps','Wait 1 second'],correct:1,explanation:'The green flag block is the starting trigger for Scratch programs.'},
      {question:'What does "repeat 3" do in coding?',options:['Runs once','Runs 3 times','Never runs','Runs forever'],correct:1,explanation:'"Repeat 3" runs the inside instructions exactly 3 times.'},
      {question:'What is a "sprite" in Scratch?',options:['A drink','A character or object in your program','A sound','A background'],correct:1,explanation:'Sprites are the characters and objects you program in Scratch.'},
    ]},
  // Y7 cross-curriculum quizzes
  { id:'curr-y7-science', year:7, subject:'Science', title:'Y7 Science: Cells & Biology', emoji:'🔬', color:'#10b981', difficulty:'Developing', timeLimit:22,
    questions:[
      {question:'What is the powerhouse of the cell?',options:['Nucleus','Ribosome','Mitochondria','Cell wall'],correct:2,explanation:'Mitochondria produce ATP energy through cellular respiration.'},
      {question:'What is photosynthesis?',options:['Breaking down food','Converting light into glucose using CO₂ and water','Breathing in cells','Digesting nutrients'],correct:1,explanation:'Photosynthesis: 6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂'},
      {question:'What type of cell has no nucleus?',options:['Animal cell','Plant cell','Prokaryotic cell','Fungal cell'],correct:2,explanation:'Prokaryotes (like bacteria) have no membrane-bound nucleus.'},
      {question:'What does DNA stand for?',options:['Deoxyribonucleic Acid','Digital Numeric Array','Dynamic Nucleic Atom','Double Nitrogen Acid'],correct:0,explanation:'DNA = Deoxyribonucleic Acid — the molecule carrying genetic information.'},
      {question:'Which organ produces insulin?',options:['Liver','Kidney','Pancreas','Stomach'],correct:2,explanation:'The pancreas secretes insulin to regulate blood glucose levels.'},
    ]},
  { id:'curr-y7-history', year:7, subject:'History', title:'Y7 History: Medieval World', emoji:'⚔️', color:'#92400e', difficulty:'Developing', timeLimit:22,
    questions:[
      {question:'In what year did William the Conqueror invade England?',options:['1066','1215','1099','1348'],correct:0,explanation:'The Battle of Hastings was in 1066 — William defeated King Harold.'},
      {question:'What document limited the power of King John in 1215?',options:['Bill of Rights','Magna Carta','The Constitution','Domesday Book'],correct:1,explanation:'Magna Carta established that even kings must follow the law.'},
      {question:'What was the Black Death?',options:['A volcanic eruption','The Great Fire','A devastating bubonic plague pandemic','A war in Asia'],correct:2,explanation:'The Black Death (1347–51) killed ~50% of Europe\'s population.'},
      {question:'What was the Crusades?',options:['Viking raids on England','A series of religious wars to control the Holy Land','A peasant revolt','A trade route'],correct:1,explanation:'The Crusades (1096–1291) were Christian military campaigns to seize Jerusalem.'},
      {question:'What was the feudal system?',options:['A banking system','A hierarchical land-ownership structure: King→Lords→Knights→Serfs','A church structure','A military ranking'],correct:1,explanation:'Feudalism organised medieval society around land exchange for military service.'},
    ]},
  { id:'curr-y7-maths', year:7, subject:'Maths', title:'Y7 Maths: Algebra Intro', emoji:'📐', color:'#6366f1', difficulty:'Developing', timeLimit:20,
    questions:[
      {question:'Solve: 2x + 3 = 11',options:['x = 3','x = 4','x = 5','x = 7'],correct:1,explanation:'2x = 8, so x = 4.'},
      {question:'What is the area of a rectangle 6cm × 4cm?',options:['10cm²','20cm²','24cm²','48cm²'],correct:2,explanation:'Area = length × width = 6 × 4 = 24cm².'},
      {question:'What is 15% of 200?',options:['15','20','30','25'],correct:2,explanation:'15% of 200 = 0.15 × 200 = 30.'},
      {question:'What is the value of 3² + 4²?',options:['14','25','49','12'],correct:1,explanation:'3² = 9, 4² = 16, 9 + 16 = 25.'},
      {question:'What is the LCM of 4 and 6?',options:['2','12','24','8'],correct:1,explanation:'LCM(4,6) = 12 — the smallest number both 4 and 6 divide into.'},
    ]},
  { id:'curr-y7-literacy', year:7, subject:'Literacy', title:'Y7 English: Language & Literature', emoji:'✍️', color:'#f43f5e', difficulty:'Developing', timeLimit:20,
    questions:[
      {question:'What is a "metaphor"?',options:['A comparison using "like" or "as"','A direct comparison — saying something IS something else','Repeating a sound','Exaggerating for effect'],correct:1,explanation:'Metaphor: "He is a lion" (not "like a lion" — that\'s a simile).'},
      {question:'What is the "protagonist" of a story?',options:['The villain','The narrator','The main character','The setting'],correct:2,explanation:'The protagonist is the central character the story follows.'},
      {question:'Which punctuation ends a question?',options:['Full stop','Exclamation mark','Question mark','Comma'],correct:2,explanation:'Questions always end with a question mark (?).'},
      {question:'What is "alliteration"?',options:['Rhyming at end of lines','Repeating the same consonant sound at the start of words','A very long sentence','A type of stanza'],correct:1,explanation:'Alliteration: "Peter Piper picked..." — repeating the "P" sound.'},
      {question:'What does "inference" mean in reading?',options:['Reading aloud','Re-reading a text','Deducing meaning not directly stated','Summarising a text'],correct:2,explanation:'Inference = reading between the lines — deducing what\'s implied.'},
    ]},
  { id:'curr-y7-coding', year:7, subject:'Coding', title:'Y7 Coding: Python Basics', emoji:'🐍', color:'#0ea5e9', difficulty:'Developing', timeLimit:20,
    questions:[
      {question:'What does print("Hello") do in Python?',options:['Prints to paper','Displays Hello in the console','Creates a variable','Nothing'],correct:1,explanation:'print() outputs text to the console/terminal.'},
      {question:'What is the correct way to create a variable in Python?',options:['var x = 5','int x = 5','x = 5','variable x = 5'],correct:2,explanation:'Python uses simple assignment: x = 5 — no type keyword needed.'},
      {question:'What does len("hello") return?',options:['4','5','6','hello'],correct:1,explanation:'len() returns the number of characters: "hello" has 5.'},
      {question:'What is a Python "list"?',options:['A sorted sequence only','An ordered, mutable collection of items','An immutable tuple','A dictionary'],correct:1,explanation:'Lists store ordered items and can be changed: [1, 2, 3]'},
      {question:'What does "for i in range(3):" do?',options:['Loops forever','Loops 3 times (i = 0,1,2)','Loops 4 times','Runs once'],correct:1,explanation:'range(3) generates 0, 1, 2 — so the loop runs 3 times.'},
    ]},
  // Y10 cross-curriculum
  { id:'curr-y10-science', year:10, subject:'Science', title:'Y10 Science: Chemistry & Physics', emoji:'⚗️', color:'#14b8a6', difficulty:'Proficient', timeLimit:20,
    questions:[
      {question:'What is the atomic number of carbon?',options:['6','12','14','8'],correct:0,explanation:'Carbon has 6 protons, giving it atomic number 6.'},
      {question:'What type of bond involves sharing electrons?',options:['Ionic bond','Covalent bond','Metallic bond','Hydrogen bond'],correct:1,explanation:'Covalent bonds form when atoms share electrons to achieve stable configurations.'},
      {question:'What is Newton\'s second law of motion?',options:['Every action has equal opposite reaction','An object stays still unless acted on by a force','Force = mass × acceleration','Energy cannot be created'],correct:2,explanation:'F = ma — force equals mass times acceleration.'},
      {question:'What is the speed of light in a vacuum?',options:['300,000 km/s','150,000 km/s','3,000 km/s','30,000 km/s'],correct:0,explanation:'Light travels at approximately 3 × 10⁸ m/s (300,000 km/s) in a vacuum.'},
      {question:'What is an isotope?',options:['An atom with a different element','An atom of the same element with different numbers of neutrons','A radioactive element','A charged atom'],correct:1,explanation:'Isotopes: same proton count, different neutron count (e.g. Carbon-12 vs Carbon-14).'},
    ]},
  { id:'curr-y10-history', year:10, subject:'History', title:'Y10 History: 20th Century', emoji:'🌍', color:'#dc2626', difficulty:'Proficient', timeLimit:20,
    questions:[
      {question:'What triggered World War I?',options:['Invasion of Poland','Assassination of Archduke Franz Ferdinand','The sinking of the Titanic','Revolution in Russia'],correct:1,explanation:'The assassination of Austro-Hungarian heir Franz Ferdinand in 1914 sparked WWI.'},
      {question:'What was the Holocaust?',options:['A famine in Russia','The Nazi genocide of 6 million Jews and others','A chemical weapons attack','A nuclear bombing'],correct:1,explanation:'The Holocaust was the systematic, state-sponsored murder of six million Jews by Nazi Germany.'},
      {question:'What year did the Berlin Wall fall?',options:['1985','1991','1989','1993'],correct:2,explanation:'The Berlin Wall fell on 9 November 1989, symbolising the end of the Cold War.'},
      {question:'What was the Cold War?',options:['A period of unusually cold weather','Geopolitical tension between the USA and USSR (1947–1991)','A war in Antarctica','A trade conflict'],correct:1,explanation:'The Cold War was ideological conflict between capitalist USA and communist USSR — no direct warfare.'},
      {question:'When did India gain independence from Britain?',options:['1935','1947','1950','1945'],correct:1,explanation:'India became independent on 15 August 1947 after campaigning led by Gandhi and others.'},
    ]},
  { id:'curr-y10-maths', year:10, subject:'Maths', title:'Y10 Maths: GCSE Tier', emoji:'📊', color:'#7c3aed', difficulty:'Proficient', timeLimit:20,
    questions:[
      {question:'What is the quadratic formula for ax² + bx + c = 0?',options:['x = -b ± √(b²-4ac) / 2a','x = b ± √(4ac-b²) / 2a','x = -b / 2a','x = √(b²-4ac)'],correct:0,explanation:'The quadratic formula: x = (-b ± √(b²−4ac)) / 2a'},
      {question:'What is the gradient of y = 3x + 2?',options:['2','3','1','5'],correct:1,explanation:'In y = mx + c, m is the gradient. Here m = 3.'},
      {question:'What is sin(30°)?',options:['√3/2','1/2','1','√2/2'],correct:1,explanation:'sin(30°) = 0.5 = 1/2. Key trig value to memorise.'},
      {question:'A circle has radius 5cm. What is its area?',options:['25π cm²','10π cm²','5π cm²','50π cm²'],correct:0,explanation:'Area = πr² = π × 5² = 25π ≈ 78.5 cm².'},
      {question:'Solve: x² − 5x + 6 = 0',options:['x=1,6','x=2,3','x=−2,−3','x=3,5'],correct:1,explanation:'Factorise: (x−2)(x−3) = 0, so x = 2 or x = 3.'},
    ]},
  { id:'curr-y10-literacy', year:10, subject:'Literacy', title:'Y10 English: Analysis Skills', emoji:'📖', color:'#e11d48', difficulty:'Proficient', timeLimit:20,
    questions:[
      {question:'What is "pathetic fallacy"?',options:['A logical error','Using weather/nature to reflect a character\'s emotions','Exaggeration for effect','An extended metaphor'],correct:1,explanation:'Pathetic fallacy: stormy weather during conflict, bright sun during happiness, etc.'},
      {question:'What does "juxtaposition" mean?',options:['Repetition for emphasis','Placing contrasting ideas side by side','A rhythmic pattern','A type of narrator'],correct:1,explanation:'Juxtaposition places opposites together to highlight contrast, e.g. light/dark, rich/poor.'},
      {question:'What is "dramatic irony"?',options:['Coincidental events','When the audience knows something a character doesn\'t','A sudden plot twist','A monologue'],correct:1,explanation:'Dramatic irony creates tension when the audience has information the character lacks.'},
      {question:'In Shakespeare\'s Macbeth, what are the three witches\' prophecies called?',options:['Omens','Riddles','The Weird Sisters\' prophecies','Curses'],correct:2,explanation:'The Weird Sisters give Macbeth prophecies that drive his ambition and downfall.'},
      {question:'What is the effect of a "short sentence" in a text?',options:['Slows pace and creates reflection','Creates fast pace, emphasis, or shock','Shows complex thought','Adds description'],correct:1,explanation:'Short sentences create impact, urgency, or dramatic effect — often used at key moments.'},
    ]},
  { id:'curr-y10-coding', year:10, subject:'Coding', title:'Y10 CS: Algorithms & Data', emoji:'⚙️', color:'#0284c7', difficulty:'Proficient', timeLimit:20,
    questions:[
      {question:'What is the time complexity of bubble sort (worst case)?',options:['O(n)','O(log n)','O(n²)','O(n log n)'],correct:2,explanation:'Bubble sort compares adjacent pairs n² times in the worst case.'},
      {question:'What data structure uses LIFO?',options:['Queue','Stack','Array','Linked list'],correct:1,explanation:'Stack = Last In, First Out. Like a stack of plates — you take from the top.'},
      {question:'What is a binary search tree?',options:['A tree sorted alphabetically','A tree where left children are smaller, right children are larger than parent','Any balanced tree','A tree with two branches only'],correct:1,explanation:'BST property: left < parent < right, enabling O(log n) search.'},
      {question:'What does SQL SELECT do?',options:['Deletes records','Updates records','Retrieves data from a database table','Creates a table'],correct:2,explanation:'SELECT retrieves rows from a table: SELECT * FROM students WHERE grade=\'A\''},
      {question:'What is the difference between RAM and ROM?',options:['RAM is permanent, ROM is temporary','RAM is temporary volatile memory; ROM is permanent non-volatile memory','No difference','ROM is faster'],correct:1,explanation:'RAM loses data on power-off (volatile); ROM retains data permanently (non-volatile).'},
    ]},
];

module.exports = { TEACHER_QUIZZES, CURRICULUM_QUIZZES };
