// ─── Teacher-Only Year Quizzes (Y1–Y11) ─────────────────────────────────────
// Progressive difficulty quizzes only accessible by verified educators
'use strict';

const TEACHER_QUIZZES = [
  {
    id: 'teacher-y1',
    year: 1, title: 'Year 1 — Digital Basics',
    description: 'Introduce young learners to computers, keyboards, and staying safe online.',
    emoji: '🖥️', color: '#4ade80', difficulty: 'Foundation',
    timeLimit: 30,
    questions: [
      { question: 'What do you use to type letters on a computer?', options: ['Keyboard','Mouse','Screen','Speaker'], correct: 0, explanation: 'A keyboard has letters and numbers you press to type.' },
      { question: 'Which device lets you click on things on the screen?', options: ['Printer','Mouse','Headphones','Camera'], correct: 1, explanation: 'A mouse moves a pointer on the screen so you can click.' },
      { question: 'What should you do if a stranger messages you online?', options: ['Reply to them','Tell a grown-up','Give your name','Ignore everyone forever'], correct: 1, explanation: 'Always tell a trusted adult if a stranger contacts you online.' },
      { question: 'What does the power button do?', options: ['Makes it louder','Turns it on or off','Opens a game','Prints a page'], correct: 1, explanation: 'The power button turns your computer on and off.' },
      { question: 'Which one is an input device?', options: ['Monitor','Printer','Keyboard','Speaker'], correct: 2, explanation: 'A keyboard is an input device — you put information IN.' },
      { question: 'What do we call pictures on a computer screen you can click?', options: ['Icons','Stickers','Photos','Drawings'], correct: 0, explanation: 'Icons are small pictures that open programs when clicked.' },
      { question: 'Is it safe to share your password with friends?', options: ['Yes, always','Only best friends','No, never','Only at school'], correct: 2, explanation: 'Never share your password — keep it secret and safe.' },
      { question: 'What does a printer do?', options: ['Plays music','Makes paper copies','Stores files','Takes photos'], correct: 1, explanation: 'A printer puts what\'s on screen onto paper.' },
      { question: 'Which is a way to stay safe online?', options: ['Click every link','Share your address','Ask a grown-up for help','Download everything'], correct: 2, explanation: 'When unsure online, ask a trusted adult for help.' },
      { question: 'What shape is the "Enter" key usually?', options: ['Circle','Triangle','Rectangle with arrow','Star'], correct: 2, explanation: 'The Enter key is usually a rectangle shape, sometimes with a bent arrow.' },
    ],
  },
  {
    id: 'teacher-y2',
    year: 2, title: 'Year 2 — Computer Explorers',
    description: 'Learn about files, folders, and simple instructions computers follow.',
    emoji: '📁', color: '#38bdf8', difficulty: 'Foundation',
    timeLimit: 28,
    questions: [
      { question: 'Where do computers store your work?', options: ['In the mouse','In files and folders','In the keyboard','In the screen'], correct: 1, explanation: 'Computers save your work in files, organized into folders.' },
      { question: 'What is an algorithm?', options: ['A type of computer','A set of step-by-step instructions','A kind of cable','A computer game'], correct: 1, explanation: 'An algorithm is a set of clear steps to solve a problem or do a task.' },
      { question: 'Which of these is software?', options: ['Monitor','A word processor','USB cable','Keyboard'], correct: 1, explanation: 'Software is programs that run ON a computer, like a word processor.' },
      { question: 'What does "save" do to your work?', options: ['Deletes it','Prints it','Keeps it stored safely','Sends it to someone'], correct: 2, explanation: 'Saving stores your work so you can open it again later.' },
      { question: 'What is the Internet?', options: ['A single computer','A network connecting millions of computers','A type of keyboard','A programming language'], correct: 1, explanation: 'The Internet is a huge network that connects computers worldwide.' },
      { question: 'Which device takes photos for the computer?', options: ['Microphone','Webcam','Printer','Hard drive'], correct: 1, explanation: 'A webcam captures pictures and video for your computer.' },
      { question: 'What happens when you "undo" something?', options: ['It saves your work','It goes back one step','It closes the program','It prints the page'], correct: 1, explanation: 'Undo reverses the last thing you did — like a time machine for one step!' },
      { question: 'In a set of instructions, what must each step be?', options: ['Long and detailed','Clear and in order','Funny and silly','Written in code'], correct: 1, explanation: 'Good instructions are clear and in the right order.' },
      { question: 'What is a "bug" in computing?', options: ['An actual insect','A mistake in a program','A computer virus','A broken screen'], correct: 1, explanation: 'A bug is a mistake or error that makes a program not work properly.' },
      { question: 'Which one stores information even when the computer is off?', options: ['RAM','Hard drive / SSD','Screen','CPU'], correct: 1, explanation: 'Hard drives and SSDs keep your files even when the power is off.' },
    ],
  },
  {
    id: 'teacher-y3',
    year: 3, title: 'Year 3 — Coding Foundations',
    description: 'Sequences, loops, and simple debugging concepts for young coders.',
    emoji: '🔄', color: '#a78bfa', difficulty: 'Developing',
    timeLimit: 25,
    questions: [
      { question: 'What is a "loop" in programming?', options: ['A type of error','An instruction that repeats','A way to delete code','A computer screen shape'], correct: 1, explanation: 'A loop repeats a set of instructions multiple times.' },
      { question: 'In Scratch, which block makes a character move?', options: ['Say block','Move 10 steps','When clicked','Forever block'], correct: 1, explanation: 'The "move 10 steps" block makes a sprite move forward.' },
      { question: 'What is "debugging"?', options: ['Adding more code','Finding and fixing mistakes','Making code run faster','Deleting a program'], correct: 1, explanation: 'Debugging means finding errors (bugs) and fixing them.' },
      { question: 'What does a "sequence" mean in coding?', options: ['Random instructions','Instructions in a specific order','A type of variable','A loop that never ends'], correct: 1, explanation: 'A sequence is instructions that run one after another in order.' },
      { question: 'What is a "variable" in simple terms?', options: ['A fixed number','A box that stores information','A type of loop','A computer part'], correct: 1, explanation: 'A variable is like a labelled box that holds a value which can change.' },
      { question: 'What will "Repeat 3: Move, Turn" do?', options: ['Move once','Move and turn 3 times','Turn 3 times only','Nothing'], correct: 1, explanation: 'It repeats "move then turn" three times.' },
      { question: 'Which is an example of an "input"?', options: ['Sound from speakers','Text on screen','Clicking a mouse button','A printed document'], correct: 2, explanation: 'Input is information going INTO the computer, like a mouse click.' },
      { question: 'What is an "output"?', options: ['Typing on keyboard','Moving the mouse','Sound from speakers','Plugging in a USB'], correct: 2, explanation: 'Output is information coming OUT of the computer, like sound.' },
      { question: 'In Scratch, what does the "if" block do?', options: ['Always runs the code inside','Runs code only when a condition is true','Repeats code forever','Stops the program'], correct: 1, explanation: 'An "if" block checks a condition and only runs when it\'s true.' },
      { question: 'Why is the ORDER of instructions important?', options: ['It doesn\'t matter','Different orders give different results','Computers ignore order','Only the first instruction matters'], correct: 1, explanation: 'The order matters because changing it changes what happens!' },
    ],
  },
  {
    id: 'teacher-y4',
    year: 4, title: 'Year 4 — Networks & Data',
    description: 'How the internet works, data representation, and digital literacy.',
    emoji: '🌐', color: '#f472b6', difficulty: 'Developing',
    timeLimit: 25,
    questions: [
      { question: 'What does "HTML" stand for?', options: ['How To Make Links','HyperText Markup Language','High Tech Modern Language','Home Tool Management Layer'], correct: 1, explanation: 'HTML = HyperText Markup Language — the code behind web pages.' },
      { question: 'What does a "router" do?', options: ['Stores files','Directs internet traffic between devices','Displays web pages','Creates passwords'], correct: 1, explanation: 'A router directs data between your devices and the internet.' },
      { question: 'What is binary?', options: ['A type of virus','A number system using only 0 and 1','A programming language','A computer brand'], correct: 1, explanation: 'Binary uses just 0s and 1s — it\'s how computers store all data.' },
      { question: 'What does "URL" stand for?', options: ['Universal Reset Link','Uniform Resource Locator','United Router Location','Under Rated Language'], correct: 1, explanation: 'A URL is the address of a web page, like its location on the internet.' },
      { question: 'What is a "search engine"?', options: ['A part of a car','A tool to find things on the internet','A type of code','A computer hardware part'], correct: 1, explanation: 'A search engine like Google helps you find information online.' },
      { question: 'How do computers store images?', options: ['As drawings','As tiny coloured dots called pixels','As text files','As sound waves'], correct: 1, explanation: 'Images are made of thousands of tiny dots (pixels), each with a colour value.' },
      { question: 'What is a "network"?', options: ['One computer alone','Two or more connected computers','A type of software','A wireless keyboard'], correct: 1, explanation: 'A network is computers linked together to share data.' },
      { question: 'What is "copyright"?', options: ['Copying someone\'s work freely','Legal protection for creators\' work','A type of font','A coding command'], correct: 1, explanation: 'Copyright protects creators — you need permission to use their work.' },
      { question: 'The number 5 in binary is:', options: ['100','110','101','111'], correct: 2, explanation: '5 in binary is 101: (1×4) + (0×2) + (1×1) = 5' },
      { question: 'What is "bandwidth"?', options: ['The width of a monitor','How much data can be sent at once','A type of cable','A music term'], correct: 1, explanation: 'Bandwidth measures how much data your connection can handle at once.' },
    ],
  },
  {
    id: 'teacher-y5',
    year: 5, title: 'Year 5 — Algorithms & Logic',
    description: 'Selection, iteration, boolean logic, and computational thinking.',
    emoji: '🧮', color: '#fb923c', difficulty: 'Intermediate',
    timeLimit: 22,
    questions: [
      { question: 'What is "selection" in programming?', options: ['Choosing random code','Making decisions with IF statements','Selecting text','Picking a programming language'], correct: 1, explanation: 'Selection means the program chooses what to do based on a condition.' },
      { question: 'What does "iteration" mean?', options: ['Stopping a program','Repeating code (loops)','Writing new code','Testing code'], correct: 1, explanation: 'Iteration means repeating — loops are iteration in action.' },
      { question: 'What is a "boolean" value?', options: ['A decimal number','True or False','A text string','A list of items'], correct: 1, explanation: 'Boolean values are either TRUE or FALSE — nothing else.' },
      { question: 'What does the operator AND do?', options: ['True if either is true','True only if BOTH are true','Always true','Reverses the value'], correct: 1, explanation: 'AND requires both conditions to be true: True AND True = True.' },
      { question: 'What is "decomposition"?', options: ['Deleting code','Breaking a big problem into smaller parts','Making code longer','A type of bug'], correct: 1, explanation: 'Decomposition = breaking complex problems into manageable pieces.' },
      { question: 'What is "abstraction"?', options: ['Making things more complicated','Removing unnecessary detail','Abstract art on screen','A type of data'], correct: 1, explanation: 'Abstraction means focusing on what matters and hiding complexity.' },
      { question: 'What does "NOT True" equal?', options: ['True','False','Null','Error'], correct: 1, explanation: 'NOT flips the value: NOT True = False.' },
      { question: 'In a flowchart, what shape represents a decision?', options: ['Rectangle','Diamond','Circle','Arrow'], correct: 1, explanation: 'Diamonds represent decision points (yes/no questions) in flowcharts.' },
      { question: 'What is "pattern recognition"?', options: ['Drawing patterns','Spotting similarities in problems','A display setting','A type of loop'], correct: 1, explanation: 'Pattern recognition means finding similarities that help solve problems.' },
      { question: 'Which loop runs a set number of times?', options: ['While loop','For loop','Infinite loop','Do loop'], correct: 1, explanation: 'A for loop runs a specific number of times: "for i = 1 to 10".' },
    ],
  },
  {
    id: 'teacher-y6',
    year: 6, title: 'Year 6 — Web & Cyber Security',
    description: 'Web development basics, online safety, encryption, and responsible tech use.',
    emoji: '🔒', color: '#ef4444', difficulty: 'Intermediate',
    timeLimit: 22,
    questions: [
      { question: 'What does "phishing" mean?', options: ['Going fishing online','Tricking people into revealing personal information','A type of game','Sending fish emojis'], correct: 1, explanation: 'Phishing = fake messages designed to steal your personal data.' },
      { question: 'What is "encryption"?', options: ['Deleting data','Scrambling data so only authorised people can read it','Compressing files','A programming language'], correct: 1, explanation: 'Encryption scrambles information into a code for security.' },
      { question: 'What does CSS do for a website?', options: ['Adds logic','Controls styling and layout','Stores data','Creates animations only'], correct: 1, explanation: 'CSS (Cascading Style Sheets) controls how a website looks.' },
      { question: 'What is "two-factor authentication"?', options: ['Two passwords','Verifying identity with two different methods','Two usernames','Logging in twice'], correct: 1, explanation: '2FA uses two methods (like password + phone code) for extra security.' },
      { question: 'What is a "cookie" on the internet?', options: ['A snack','A small file that stores website preferences','A virus','A bookmark'], correct: 1, explanation: 'Cookies store small pieces of data about your visit to a website.' },
      { question: 'What does "HTTPS" mean compared to HTTP?', options: ['It\'s faster','It\'s encrypted and secure','It\'s newer','It has more pages'], correct: 1, explanation: 'HTTPS adds encryption — the "S" stands for Secure.' },
      { question: 'What is "malware"?', options: ['Good software','Software designed to harm or exploit','A male programmer','A type of hardware'], correct: 1, explanation: 'Malware = malicious software: viruses, trojans, ransomware, etc.' },
      { question: 'What is a "firewall"?', options: ['A wall on fire','A security system that monitors network traffic','A type of router','A coding language'], correct: 1, explanation: 'A firewall monitors and controls incoming/outgoing network traffic.' },
      { question: 'What is the "digital footprint"?', options: ['A fingerprint scanner','The trail of data you leave online','A type of file','A virtual shoe'], correct: 1, explanation: 'Your digital footprint is all the data traces you leave when using the internet.' },
      { question: 'What is "open source" software?', options: ['Software you buy','Software whose code anyone can view and modify','Broken software','Software without a name'], correct: 1, explanation: 'Open source means the code is publicly available for anyone to use and improve.' },
    ],
  },
  {
    id: 'teacher-y7',
    year: 7, title: 'Year 7 — Programming Principles',
    description: 'Variables, data types, conditionals, and real Python/JS syntax.',
    emoji: '🐍', color: '#3b82f6', difficulty: 'Secure',
    timeLimit: 20,
    questions: [
      { question: 'In Python, what does print("Hello") do?', options: ['Saves "Hello" to a file','Displays "Hello" on screen','Creates a variable','Deletes the word Hello'], correct: 1, explanation: 'print() outputs text to the screen — it\'s the most basic output command.' },
      { question: 'What data type is the value 3.14?', options: ['Integer','String','Float','Boolean'], correct: 2, explanation: '3.14 has a decimal point, making it a float (floating-point number).' },
      { question: 'What does x = x + 1 do?', options: ['Sets x to 1','Increases x by 1','Creates an error','Compares x to 1'], correct: 1, explanation: 'It takes the current value of x, adds 1, and stores the result back in x.' },
      { question: 'What is a "string"?', options: ['A number','Text data enclosed in quotes','A boolean','A list'], correct: 1, explanation: 'A string is text — characters between quotes like "Hello World".' },
      { question: 'What will "5" + "3" give in JavaScript?', options: ['8','53','Error','15'], correct: 1, explanation: 'When both are strings, + concatenates: "5" + "3" = "53".' },
      { question: 'What is an "array" (or list)?', options: ['A single value','A collection of values in order','A function','A boolean'], correct: 1, explanation: 'An array/list stores multiple values in a single variable.' },
      { question: 'What does == check for?', options: ['Assignment','Equality (are two values the same?)','Greater than','Addition'], correct: 1, explanation: '== checks if two values are equal. Different from = which assigns.' },
      { question: 'What is a "function"?', options: ['A variable type','A reusable block of code','A loop','A data file'], correct: 1, explanation: 'Functions are reusable code blocks you can call by name.' },
      { question: 'What happens if you divide by zero?', options: ['Returns 0','Causes an error','Returns infinity','Returns 1'], correct: 1, explanation: 'Dividing by zero causes an error in most programming languages.' },
      { question: 'What is "pseudocode"?', options: ['Real Python code','Plain-language description of an algorithm','A broken program','A type of encryption'], correct: 1, explanation: 'Pseudocode describes logic in plain language before writing actual code.' },
    ],
  },
  {
    id: 'teacher-y8',
    year: 8, title: 'Year 8 — Data & Systems',
    description: 'Databases, binary arithmetic, hardware architecture, and operating systems.',
    emoji: '💾', color: '#8b5cf6', difficulty: 'Secure',
    timeLimit: 20,
    questions: [
      { question: 'What is a "database"?', options: ['A spreadsheet','An organised collection of structured data','A web browser','A type of code'], correct: 1, explanation: 'A database stores and organises large amounts of data efficiently.' },
      { question: 'What does "SQL" stand for?', options: ['Simple Question Language','Structured Query Language','System Quality Level','Standard Quick Lookup'], correct: 1, explanation: 'SQL = Structured Query Language — used to manage databases.' },
      { question: 'What is the binary value of decimal 10?', options: ['1010','1100','1001','1110'], correct: 0, explanation: '10 in binary: 8+2 = 1010 (8,4,2,1 → 1,0,1,0).' },
      { question: 'What is the CPU?', options: ['A storage device','The central processing unit — the brain','A display unit','A network card'], correct: 1, explanation: 'The CPU processes instructions — it\'s the "brain" of the computer.' },
      { question: 'What is RAM used for?', options: ['Long-term storage','Temporary fast memory for running programs','Connecting to WiFi','Displaying graphics'], correct: 1, explanation: 'RAM holds data for programs currently running — it\'s fast but temporary.' },
      { question: 'What is an "operating system"?', options: ['An app','Software that manages hardware and software resources','A type of CPU','A network'], correct: 1, explanation: 'The OS (Windows, macOS, Linux) manages everything on your computer.' },
      { question: 'How many bits are in a byte?', options: ['4','8','16','32'], correct: 1, explanation: '1 byte = 8 bits. A bit is a single 0 or 1.' },
      { question: 'What does "SELECT * FROM students" do in SQL?', options: ['Deletes all students','Gets all data from the students table','Creates a new table','Updates a student'], correct: 1, explanation: 'SELECT * FROM students retrieves all records from the students table.' },
      { question: 'What is "cloud computing"?', options: ['Computing in the sky','Using remote servers over the internet','A weather app','A type of hard drive'], correct: 1, explanation: 'Cloud computing uses remote servers accessed via the internet.' },
      { question: 'What is "hexadecimal"?', options: ['Base-2','Base-10','Base-16','Base-8'], correct: 2, explanation: 'Hex is base-16, using digits 0-9 and letters A-F. Common for colours.' },
    ],
  },
  {
    id: 'teacher-y9',
    year: 9, title: 'Year 9 — Advanced Programming',
    description: 'OOP concepts, file handling, error handling, and algorithm efficiency.',
    emoji: '⚙️', color: '#06b6d4', difficulty: 'Advanced',
    timeLimit: 18,
    questions: [
      { question: 'What is "Object-Oriented Programming"?', options: ['Programming with numbers','Programming using objects that combine data and methods','A visual programming language','Programming without variables'], correct: 1, explanation: 'OOP organises code into objects — bundles of data (properties) and actions (methods).' },
      { question: 'What is "inheritance" in OOP?', options: ['Copying a file','A class receiving properties/methods from a parent class','A type of loop','Deleting old code'], correct: 1, explanation: 'Inheritance lets a class "inherit" features from another class.' },
      { question: 'What is a "try-catch" block used for?', options: ['Catching bugs at compile time','Handling errors gracefully at runtime','Trying new languages','Testing performance'], correct: 1, explanation: 'Try-catch lets your program handle errors without crashing.' },
      { question: 'What is "Big O notation" used for?', options: ['Grading code','Describing algorithm efficiency/speed','A programming language','File sizes'], correct: 1, explanation: 'Big O describes how an algorithm\'s time/space scales with input size.' },
      { question: 'What is O(n) time complexity?', options: ['Constant time','Linear — grows proportionally with input','Quadratic','Logarithmic'], correct: 1, explanation: 'O(n) means the time grows linearly: double the input, double the time.' },
      { question: 'What is a "class" in OOP?', options: ['A school class','A blueprint for creating objects','A type of variable','A function'], correct: 1, explanation: 'A class is a template that defines what an object will look like and do.' },
      { question: 'What does "encapsulation" mean?', options: ['Making code public','Hiding internal details and exposing only what\'s needed','Encrypting data','Compressing files'], correct: 1, explanation: 'Encapsulation hides an object\'s internal workings, showing only an interface.' },
      { question: 'What is "recursion"?', options: ['A loop','A function that calls itself','An error','A data type'], correct: 1, explanation: 'Recursion is when a function calls itself to solve smaller sub-problems.' },
      { question: 'What is a "stack overflow"?', options: ['Too much data in a database','When recursion goes too deep, filling the call stack','A website','When RAM is full'], correct: 1, explanation: 'A stack overflow happens when too many function calls pile up.' },
      { question: 'What is "polymorphism"?', options: ['Multiple variables','Objects of different classes responding to the same method call','A data structure','A network protocol'], correct: 1, explanation: 'Polymorphism = same method name, different behaviour depending on the object.' },
    ],
  },
  {
    id: 'teacher-y10',
    year: 10, title: 'Year 10 — GCSE Computer Science',
    description: 'Exam-level: logic gates, sorting algorithms, data representation, and ethics.',
    emoji: '📐', color: '#eab308', difficulty: 'Advanced',
    timeLimit: 18,
    questions: [
      { question: 'What is the output of AND gate when inputs are 1 and 0?', options: ['1','0','Undefined','Error'], correct: 1, explanation: 'AND gate: both inputs must be 1 for output 1. 1 AND 0 = 0.' },
      { question: 'What is the time complexity of bubble sort (worst case)?', options: ['O(n)','O(n log n)','O(n²)','O(1)'], correct: 2, explanation: 'Bubble sort compares every pair — worst case is O(n²).' },
      { question: 'What does an OR gate output when both inputs are 0?', options: ['1','0','Error','Undefined'], correct: 1, explanation: 'OR gate: at least one input must be 1 for output 1. 0 OR 0 = 0.' },
      { question: 'How many unique values can 8 bits represent?', options: ['8','128','256','512'], correct: 2, explanation: '2⁸ = 256 unique values (0 to 255).' },
      { question: 'What is "normalisation" in databases?', options: ['Making data normal','Organising data to reduce redundancy','Sorting alphabetically','Encrypting data'], correct: 1, explanation: 'Normalisation structures databases to minimise data duplication.' },
      { question: 'Which sorting algorithm uses "divide and conquer"?', options: ['Bubble sort','Insertion sort','Merge sort','Selection sort'], correct: 2, explanation: 'Merge sort splits the list in half recursively, then merges sorted halves.' },
      { question: 'What is "lossy" compression?', options: ['Compression with no data loss','Compression that permanently removes some data','A broken file','An encryption method'], correct: 1, explanation: 'Lossy compression (like JPEG) permanently removes data to reduce file size.' },
      { question: 'What is a "logic gate"?', options: ['A physical gate','An electronic circuit performing a boolean function','A software firewall','A type of cable'], correct: 1, explanation: 'Logic gates are circuits that implement boolean operations (AND, OR, NOT, etc.).' },
      { question: 'What is "fetch-decode-execute"?', options: ['A dance move','The CPU cycle for processing instructions','A file transfer protocol','A debugging method'], correct: 1, explanation: 'The CPU cycle: fetch instruction from memory, decode it, execute it. Repeat.' },
      { question: 'What is an "ethical issue" in computing?', options: ['A coding error','A question about right and wrong in technology use','A hardware problem','A software update'], correct: 1, explanation: 'Ethical issues include privacy, AI bias, surveillance, digital divide, and more.' },
    ],
  },
  {
    id: 'teacher-y11',
    year: 11, title: 'Year 11 — Exam Mastery',
    description: 'Final-year challenge: networking protocols, advanced algorithms, and theory.',
    emoji: '🎓', color: '#dc2626', difficulty: 'Expert',
    timeLimit: 15,
    questions: [
      { question: 'What layer of the TCP/IP model handles routing?', options: ['Application','Transport','Internet (Network)','Link'], correct: 2, explanation: 'The Internet layer (IP) handles addressing and routing packets.' },
      { question: 'What is the worst-case complexity of binary search?', options: ['O(n)','O(n²)','O(log n)','O(1)'], correct: 2, explanation: 'Binary search halves the search space each step: O(log n).' },
      { question: 'What is "Dijkstra\'s algorithm" used for?', options: ['Sorting data','Finding shortest path in a weighted graph','Encrypting data','Compressing files'], correct: 1, explanation: 'Dijkstra\'s finds the shortest path between nodes in a weighted graph.' },
      { question: 'What does TCP guarantee that UDP does not?', options: ['Speed','Reliable, ordered delivery of data','Encryption','Compression'], correct: 1, explanation: 'TCP guarantees packets arrive correctly and in order. UDP is faster but unreliable.' },
      { question: 'In a binary tree, what is an "in-order traversal"?', options: ['Root, Left, Right','Left, Root, Right','Left, Right, Root','Right, Root, Left'], correct: 1, explanation: 'In-order: visit left subtree, then root, then right subtree.' },
      { question: 'What is "hashing" used for?', options: ['Sorting data','Mapping data to a fixed-size value for fast lookup','Drawing graphics','Network routing'], correct: 1, explanation: 'Hashing converts data into a fixed-size hash — used in hash tables and security.' },
      { question: 'What is the difference between "compiler" and "interpreter"?', options: ['No difference','Compiler translates all at once; interpreter line-by-line','Compiler is slower','Interpreter is for hardware'], correct: 1, explanation: 'A compiler translates the entire program before running; an interpreter does it line by line.' },
      { question: 'What does "ACID" stand for in databases?', options: ['Atomicity, Consistency, Isolation, Durability','Advanced Computing Interface Design','Automated Compiled Indexed Data','None of these'], correct: 0, explanation: 'ACID ensures reliable database transactions: Atomicity, Consistency, Isolation, Durability.' },
      { question: 'What is "virtual memory"?', options: ['Cloud storage','Using hard drive space as extra RAM','Imaginary memory','Memory in a virtual machine only'], correct: 1, explanation: 'Virtual memory uses disk space to extend RAM when physical memory is full.' },
      { question: 'What is the "halting problem"?', options: ['Stopping a loop','The proven impossibility of determining if any program will finish','A CPU error','A network timeout'], correct: 1, explanation: 'Alan Turing proved no algorithm can determine if every program will eventually halt.' },
    ],
  },
];

module.exports = { TEACHER_QUIZZES };
