'use strict';

/**
 * PolitiBattle — Politician Data
 * 50 Political Figures with types, base stats, and movesets.
 *
 * Types: Republican, Democrat, Libertarian, Green, Socialist,
 *        Authoritarian, Centrist, Populist, Corporate, Revolutionary
 *
 * Each politician gets 1-2 SIGNATURE moves (unique to them) + 2-3 type moves.
 * Stats: hp, atk, def, spa, spd, spe (base stats, scaled like Pokémon ~40-130)
 */

// ── TYPE MOVES (shared pool, anyone can learn if type matches) ──────────────
const TYPE_MOVES = {
  // REPUBLICAN
  taxCut:        { name: 'Tax Cut Slash', type: 'Republican', category: 'special', power: 80, accuracy: 100, description: 'Slashes the budget for massive damage.', effect: null },
  filibuster:    { name: 'Filibuster', type: 'Republican', category: 'status', power: 0, accuracy: 90, description: 'Talks endlessly, putting the foe to sleep.', effect: { status: 'sleep' } },
  gunLobby:      { name: 'Gun Lobby Barrage', type: 'Republican', category: 'physical', power: 90, accuracy: 85, description: 'A barrage backed by lobby money.', effect: { chance: 20, flinch: true } },
  redWave:       { name: 'Red Wave', type: 'Republican', category: 'special', power: 70, accuracy: 100, description: 'A sweeping wave of conservative energy.', effect: null },
  // DEMOCRAT
  cancelCulture: { name: 'Cancel Culture', type: 'Democrat', category: 'special', power: 75, accuracy: 95, description: 'Cancels the opponent from relevance.', effect: { chance: 30, statBoost: { spa: -1 }, self: false } },
  blueWave:      { name: 'Blue Wave', type: 'Democrat', category: 'special', power: 70, accuracy: 100, description: 'A wave of progressive energy.', effect: null },
  socialProgram: { name: 'Social Safety Net', type: 'Democrat', category: 'status', power: 0, accuracy: 100, description: 'Heals with the power of social programs.', effect: { heal: 0.5, self: true } },
  factCheck:     { name: 'Fact Check', type: 'Democrat', category: 'special', power: 60, accuracy: 100, description: 'Attacks with undeniable facts.', effect: { chance: 30, statBoost: { spa: -1 }, self: false } },
  // LIBERTARIAN
  deregulate:    { name: 'Deregulate', type: 'Libertarian', category: 'status', power: 0, accuracy: 100, description: 'Removes all restrictions. Boosts speed sharply.', effect: { statBoost: { spe: 2 }, self: true } },
  freeMkt:       { name: 'Free Market Force', type: 'Libertarian', category: 'special', power: 85, accuracy: 90, description: 'The invisible hand strikes hard.', effect: null },
  dontTread:     { name: 'Don\'t Tread On Me', type: 'Libertarian', category: 'physical', power: 70, accuracy: 100, description: 'Retaliatory strike — don\'t mess with liberty.', effect: null },
  // GREEN
  solarBeam:     { name: 'Solar Beam Blast', type: 'Green', category: 'special', power: 90, accuracy: 90, description: 'Harnesses actual solar power to attack.', effect: null },
  recycle:       { name: 'Recycle Restore', type: 'Green', category: 'status', power: 0, accuracy: 100, description: 'Recycles energy to heal.', effect: { heal: 0.3, self: true } },
  treeHug:       { name: 'Tree Hugger Shield', type: 'Green', category: 'status', power: 0, accuracy: 100, description: 'Hugs a tree for defense.', effect: { statBoost: { def: 1, spd: 1 }, self: true } },
  // SOCIALIST
  redistribute:  { name: 'Redistribute', type: 'Socialist', category: 'special', power: 80, accuracy: 100, description: 'Takes from their stats and redistributes.', effect: { statBoost: { atk: -1 }, self: false } },
  unionStrike:   { name: 'Union Strike', type: 'Socialist', category: 'physical', power: 85, accuracy: 90, description: 'Workers unite for a massive strike.', effect: null },
  classWar:      { name: 'Class Warfare', type: 'Socialist', category: 'special', power: 95, accuracy: 80, description: 'Rallies the workers for revolution.', effect: null },
  // AUTHORITARIAN
  executiveOrder:{ name: 'Executive Order', type: 'Authoritarian', category: 'special', power: 100, accuracy: 85, description: 'An unchallengeable decree of power.', effect: null },
  propaganda:    { name: 'Propaganda', type: 'Authoritarian', category: 'status', power: 0, accuracy: 90, description: 'Confuses the opponent with propaganda.', effect: { statBoost: { spa: -2 }, self: false } },
  ironCurtain:   { name: 'Iron Curtain', type: 'Authoritarian', category: 'status', power: 0, accuracy: 100, description: 'Raises an impenetrable wall.', effect: { statBoost: { def: 2, spd: 2 }, self: true } },
  secretPolice:  { name: 'Secret Police', type: 'Authoritarian', category: 'physical', power: 90, accuracy: 85, description: 'A shadowy strike from the state.', effect: { chance: 30, status: 'paralysis' } },
  // CENTRIST
  compromise:    { name: 'Compromise', type: 'Centrist', category: 'status', power: 0, accuracy: 100, description: 'Finds middle ground. Heals and boosts.', effect: { heal: 0.25, statBoost: { def: 1 }, self: true } },
  bipartisan:    { name: 'Bipartisan Beam', type: 'Centrist', category: 'special', power: 75, accuracy: 100, description: 'Attacks from both sides at once.', effect: null },
  moderateSlap:  { name: 'Moderate Slap', type: 'Centrist', category: 'physical', power: 60, accuracy: 100, description: 'A measured, sensible attack.', effect: null },
  // POPULIST
  rallyBase:     { name: 'Rally the Base', type: 'Populist', category: 'status', power: 0, accuracy: 100, description: 'Fires up the crowd. Boosts attack and sp.atk.', effect: { statBoost: { atk: 1, spa: 1 }, self: true } },
  crowdSurge:    { name: 'Crowd Surge', type: 'Populist', category: 'physical', power: 85, accuracy: 90, description: 'A massive wave of supporters crashes in.', effect: null },
  pitchfork:     { name: 'Pitchfork Fury', type: 'Populist', category: 'physical', power: 70, accuracy: 100, description: 'The angry mob attacks!', effect: { chance: 20, flinch: true } },
  // CORPORATE
  lobbyist:      { name: 'Lobbyist Strike', type: 'Corporate', category: 'special', power: 80, accuracy: 95, description: 'Money talks, and it hurts.', effect: null },
  goldenPara:    { name: 'Golden Parachute', type: 'Corporate', category: 'status', power: 0, accuracy: 100, description: 'Escapes consequences while healing.', effect: { heal: 0.4, self: true } },
  hostile:       { name: 'Hostile Takeover', type: 'Corporate', category: 'special', power: 95, accuracy: 80, description: 'A ruthless corporate acquisition.', effect: { chance: 20, statBoost: { def: -1 }, self: false } },
  // REVOLUTIONARY
  uprising:      { name: 'Uprising', type: 'Revolutionary', category: 'physical', power: 90, accuracy: 85, description: 'The people rise up!', effect: null },
  guillotine:    { name: 'Political Guillotine', type: 'Revolutionary', category: 'physical', power: 110, accuracy: 70, description: 'A devastating revolutionary strike.', effect: null },
  manifesto:     { name: 'Manifesto', type: 'Revolutionary', category: 'status', power: 0, accuracy: 100, description: 'Publishes a manifesto. Sharply raises Sp.Atk.', effect: { statBoost: { spa: 2 }, self: true } },
  // HAZARDS (any type can learn)
  stealthRock:   { name: 'Scandal Stones', type: 'Centrist', category: 'status', power: 0, accuracy: 100, description: 'Sets up damaging scandals for switching opponents.', effect: { hazard: 'stealthRock' } },
  spikes:        { name: 'Policy Spikes', type: 'Republican', category: 'status', power: 0, accuracy: 100, description: 'Lays policy traps on the ground.', effect: { hazard: 'spikes' } },
  stickyWeb:     { name: 'Bureaucracy Web', type: 'Corporate', category: 'status', power: 0, accuracy: 100, description: 'Slows down anyone who enters with bureaucratic tape.', effect: { hazard: 'stickyWeb' } },
};

// ── SIGNATURE MOVES ─────────────────────────────────────────────────────────
const SIG = {
  obamahameha:      { name: 'Obamahameha', type: 'Democrat', category: 'special', power: 110, accuracy: 90, description: 'A legendary beam of hope and change.', effect: null },
  yesWeCan:         { name: 'Yes We Can Cannon', type: 'Democrat', category: 'special', power: 85, accuracy: 100, description: 'Inspires allies while blasting foes.', effect: { statBoost: { spa: 1 }, self: true } },
  bidenBlast:       { name: 'Biden Blast', type: 'Democrat', category: 'special', power: 95, accuracy: 85, description: 'A confused but powerful blast of energy.', effect: { chance: 20, status: 'paralysis' } },
  noMalarkey:       { name: 'No Malarkey!', type: 'Centrist', category: 'physical', power: 75, accuracy: 100, description: 'Calls out the malarkey with a firm slap.', effect: null },
  deportTeleport:   { name: 'Deportation Teleportation', type: 'Authoritarian', category: 'special', power: 100, accuracy: 90, description: 'Teleports opponents out of the arena.', effect: { chance: 20, statBoost: { spe: -1 }, self: false } },
  artOfDeal:        { name: 'Art of the Deal', type: 'Corporate', category: 'status', power: 0, accuracy: 100, description: 'Makes a tremendous deal. Sharply raises Attack.', effect: { statBoost: { atk: 2 }, self: true } },
  bushLeague:       { name: 'Bush League Brawl', type: 'Republican', category: 'physical', power: 90, accuracy: 90, description: 'A down-and-dirty Texas brawl.', effect: null },
  missionAccomp:    { name: 'Mission Accomplished', type: 'Republican', category: 'status', power: 0, accuracy: 100, description: 'Declares victory prematurely. Boosts all stats.', effect: { statBoost: { atk: 1, def: 1, spe: 1 }, self: true } },
  cheney_shot:      { name: 'Friendly Fire', type: 'Republican', category: 'physical', power: 120, accuracy: 70, description: 'Accidentally shoots with devastating power.', effect: { recoil: 0.25 } },
  darkEnergy:       { name: 'Dark Energy Policy', type: 'Corporate', category: 'special', power: 90, accuracy: 90, description: 'Fuels an attack with oil money.', effect: null },
  bernBurn:         { name: 'Bern Burn', type: 'Socialist', category: 'special', power: 95, accuracy: 90, description: 'Feeling the Bern! A fiery socialist blast.', effect: { chance: 30, status: 'burn' } },
  wallStreetBust:   { name: 'Wall Street Buster', type: 'Socialist', category: 'special', power: 80, accuracy: 100, description: 'Breaks up big banks for damage.', effect: { statBoost: { spa: -1 }, self: false } },
  hillaryMail:      { name: 'Email Blast', type: 'Democrat', category: 'special', power: 85, accuracy: 85, description: 'A scandalous email attack that confuses.', effect: { chance: 30, statBoost: { spa: -1 }, self: false } },
  deleteEmails:     { name: 'Delete Evidence', type: 'Corporate', category: 'status', power: 0, accuracy: 100, description: 'Deletes evidence to boost evasion.', effect: { statBoost: { spe: 2 }, self: true } },
  putinPunch:       { name: 'Putin\'s Iron Fist', type: 'Authoritarian', category: 'physical', power: 120, accuracy: 85, description: 'A devastating authoritarian strike.', effect: { chance: 30, flinch: true } },
  novichok:         { name: 'Nerve Agent', type: 'Authoritarian', category: 'status', power: 0, accuracy: 85, description: 'A terrifying toxic attack.', effect: { status: 'toxic' } },
  hitlerBlitz:      { name: 'Blitzkrieg', type: 'Authoritarian', category: 'physical', power: 130, accuracy: 75, description: 'An overwhelming lightning war assault.', effect: { recoil: 0.33 } },
  naziPropaganda:   { name: 'Propaganda Machine', type: 'Authoritarian', category: 'status', power: 0, accuracy: 90, description: 'Brainwashes with propaganda.', effect: { statBoost: { spa: -2, spd: -1 }, self: false } },
  reaganomics:      { name: 'Reaganomics', type: 'Corporate', category: 'special', power: 85, accuracy: 95, description: 'Trickle-down damage — hits hard at the top.', effect: null },
  tearDownWall:     { name: 'Tear Down This Wall!', type: 'Republican', category: 'physical', power: 100, accuracy: 90, description: 'Smashes through all defenses.', effect: { statBoost: { def: -1 }, self: false } },
  aocClap:          { name: 'AOC Clapback', type: 'Socialist', category: 'special', power: 80, accuracy: 100, description: 'A devastating Twitter clapback.', effect: { chance: 20, statBoost: { spa: -1 }, self: false } },
  greenNewDeal:     { name: 'Green New Deal', type: 'Green', category: 'status', power: 0, accuracy: 100, description: 'Transforms the battlefield. Boosts all stats.', effect: { statBoost: { atk: 1, def: 1, spa: 1, spd: 1, spe: 1 }, self: true } },
  pelosi_clap:      { name: 'Sarcastic Clap', type: 'Democrat', category: 'special', power: 75, accuracy: 100, description: 'A patronizing slow clap that burns.', effect: { chance: 40, status: 'burn' } },
  pelosiRip:        { name: 'Speech Ripper', type: 'Democrat', category: 'physical', power: 85, accuracy: 95, description: 'Rips up the opponent\'s plans.', effect: null },
  poopootin:        { name: 'Nuclear Option', type: 'Authoritarian', category: 'special', power: 150, accuracy: 60, description: 'The ultimate threat. Massive power, terrible accuracy.', effect: { recoil: 0.5 } },
  tedCruzFlee:      { name: 'Cancun Escape', type: 'Republican', category: 'status', power: 0, accuracy: 100, description: 'Flees to Cancun. Heals but lowers reputation.', effect: { heal: 0.5, statBoost: { def: -1 }, self: true } },
  zodiacKill:       { name: 'Zodiac Cipher', type: 'Republican', category: 'special', power: 90, accuracy: 85, description: 'A mysterious, unsolvable attack.', effect: { chance: 30, status: 'paralysis' } },
  mcconnellShell:   { name: 'Turtle Shell', type: 'Republican', category: 'status', power: 0, accuracy: 100, description: 'Retreats into shell. Massively raises defense.', effect: { statBoost: { def: 2, spd: 2 }, self: true } },
  mcconnellBlock:   { name: 'Senate Block', type: 'Republican', category: 'status', power: 0, accuracy: 100, description: 'Blocks everything. Opponent\'s speed falls.', effect: { statBoost: { spe: -2 }, self: false } },
  kamalaLaugh:      { name: 'Kamala Cackle', type: 'Democrat', category: 'special', power: 70, accuracy: 100, description: 'An infectious laugh that confuses.', effect: { chance: 30, statBoost: { spa: -1 }, self: false } },
  prosecutorSlam:   { name: 'Prosecutor\'s Slam', type: 'Democrat', category: 'special', power: 90, accuracy: 90, description: 'Cross-examines the opponent into submission.', effect: null },
  mittRomney:       { name: 'Binder Bash', type: 'Republican', category: 'physical', power: 75, accuracy: 100, description: 'Throws a binder full of policies.', effect: null },
  romneyFlip:       { name: 'Position Flip', type: 'Centrist', category: 'status', power: 0, accuracy: 100, description: 'Flips positions to gain advantage.', effect: { statBoost: { spe: 1, spa: 1 }, self: true } },
  muskTweet:        { name: 'Shitpost Storm', type: 'Libertarian', category: 'special', power: 75, accuracy: 85, description: 'A chaotic barrage of tweets.', effect: { chance: 30, statBoost: { spa: -1 }, self: false } },
  muskRocket:       { name: 'Rocket Launch', type: 'Corporate', category: 'special', power: 110, accuracy: 80, description: 'Launches a rocket at the opponent. Explosive.', effect: null },
  thatcherSmash:    { name: 'Iron Lady Strike', type: 'Republican', category: 'physical', power: 100, accuracy: 90, description: 'An unyielding iron strike.', effect: null },
  thatcherCrush:    { name: 'Union Crusher', type: 'Corporate', category: 'special', power: 85, accuracy: 95, description: 'Crushes organized resistance.', effect: null },
  zelensky:         { name: 'Stand Your Ground', type: 'Revolutionary', category: 'physical', power: 100, accuracy: 95, description: '"I need ammo, not a ride." Hits with courage.', effect: null },
  zelenskyInspire:  { name: 'Inspire Resistance', type: 'Revolutionary', category: 'status', power: 0, accuracy: 100, description: 'Inspires the team. Raises attack and sp.def.', effect: { statBoost: { atk: 1, spd: 1 }, self: true } },
  jfkMoon:          { name: 'Moonshot', type: 'Democrat', category: 'special', power: 95, accuracy: 90, description: 'We choose to go to the moon! Reaches for the stars.', effect: null },
  jfkCharm:         { name: 'Camelot Charm', type: 'Centrist', category: 'status', power: 0, accuracy: 100, description: 'Charms with style and grace.', effect: { statBoost: { spa: 1, spe: 1 }, self: true } },
  nixonTrick:       { name: 'Tricky Dick', type: 'Republican', category: 'special', power: 80, accuracy: 90, description: 'A tricky, underhanded attack.', effect: { chance: 30, status: 'paralysis' } },
  watergate:        { name: 'Watergate Scandal', type: 'Republican', category: 'status', power: 0, accuracy: 85, description: 'Exposes a scandal. Sharply lowers opponent\'s stats.', effect: { statBoost: { def: -2, spd: -2 }, self: false } },
  jinpingGrip:      { name: 'Social Credit Crush', type: 'Authoritarian', category: 'special', power: 95, accuracy: 90, description: 'Lowers your social credit to zero.', effect: { chance: 20, statBoost: { spe: -1 }, self: false } },
  jinpingCensor:    { name: 'Great Firewall', type: 'Authoritarian', category: 'status', power: 0, accuracy: 100, description: 'Censors opponent\'s strongest moves.', effect: { statBoost: { spa: -2 }, self: false } },
  kimNuke:          { name: 'Nuclear Test', type: 'Authoritarian', category: 'special', power: 130, accuracy: 65, description: 'Launches a test missile. Unreliable but devastating.', effect: { recoil: 0.25 } },
  kimParade:        { name: 'Military Parade', type: 'Authoritarian', category: 'status', power: 0, accuracy: 100, description: 'Shows off military might.', effect: { statBoost: { atk: 2 }, self: true } },
  goreInternet:     { name: 'I Invented This!', type: 'Green', category: 'special', power: 80, accuracy: 95, description: 'Claims to have invented the attack.', effect: null },
  inconvenientTruth:{ name: 'Inconvenient Truth', type: 'Green', category: 'special', power: 90, accuracy: 90, description: 'Hits with an undeniable climate truth.', effect: { chance: 30, status: 'burn' } },
  cheGuevara:       { name: 'Viva La Revolución', type: 'Revolutionary', category: 'physical', power: 100, accuracy: 90, description: 'A passionate revolutionary charge.', effect: null },
  guerrilla:        { name: 'Guerrilla Tactics', type: 'Revolutionary', category: 'physical', power: 70, accuracy: 100, description: 'Strikes from the shadows.', effect: { statBoost: { spe: 1 }, self: true } },
  merkelStare:      { name: 'Merkel Stare', type: 'Centrist', category: 'special', power: 75, accuracy: 100, description: 'An intimidating stare of disappointment.', effect: { chance: 40, statBoost: { atk: -1 }, self: false } },
  merkelScience:    { name: 'Scientific Method', type: 'Centrist', category: 'special', power: 85, accuracy: 95, description: 'Attacks with cold, rational precision.', effect: null },
  trudeau:          { name: 'Apology Tour', type: 'Democrat', category: 'status', power: 0, accuracy: 100, description: 'Apologizes so sincerely it heals.', effect: { heal: 0.4, self: true } },
  trudeauBox:       { name: 'Boxing Match', type: 'Centrist', category: 'physical', power: 85, accuracy: 90, description: 'Throws hands with surprising skill.', effect: null },
  borisBuffoon:     { name: 'Bumbling Blitz', type: 'Populist', category: 'physical', power: 80, accuracy: 80, description: 'Charges chaotically. Somehow effective.', effect: { chance: 30, flinch: true } },
  borisBrexit:      { name: 'Brexit Bash', type: 'Populist', category: 'special', power: 90, accuracy: 85, description: 'Divorces from the opponent\'s game plan.', effect: null },
  popeBlessing:     { name: 'Papal Blessing', type: 'Centrist', category: 'status', power: 0, accuracy: 100, description: 'Blesses the team. Full heal.', effect: { heal: 0.5, self: true } },
  popeSmite:        { name: 'Holy Smite', type: 'Centrist', category: 'special', power: 90, accuracy: 90, description: 'Divine judgment rains down.', effect: null },
  gandhi:           { name: 'Peaceful Protest', type: 'Green', category: 'status', power: 0, accuracy: 100, description: 'Non-violent resistance. Massively raises Sp.Def.', effect: { statBoost: { spd: 2, def: 1 }, self: true } },
  gandhiMarch:      { name: 'Salt March', type: 'Revolutionary', category: 'physical', power: 75, accuracy: 100, description: 'A long march that builds unstoppable momentum.', effect: { statBoost: { atk: 1 }, self: true } },
  mandela:          { name: 'Long Walk to Freedom', type: 'Revolutionary', category: 'status', power: 0, accuracy: 100, description: 'Endures to raise all defenses.', effect: { statBoost: { def: 2, spd: 2 }, self: true } },
  mandelaUnite:     { name: 'Rainbow Nation', type: 'Centrist', category: 'special', power: 85, accuracy: 95, description: 'Unites all types for a powerful blast.', effect: null },
  lincolnAxe:       { name: 'Rail Splitter', type: 'Republican', category: 'physical', power: 100, accuracy: 90, description: 'Splits the opposition with an axe.', effect: null },
  emancipate:       { name: 'Emancipation', type: 'Revolutionary', category: 'status', power: 0, accuracy: 100, description: 'Frees the team from status conditions. Heals.', effect: { heal: 0.3, self: true } },
  fdrDeal:          { name: 'New Deal', type: 'Democrat', category: 'status', power: 0, accuracy: 100, description: 'Massive government spending heals and boosts.', effect: { heal: 0.3, statBoost: { def: 1, spd: 1 }, self: true } },
  fdrFireside:      { name: 'Fireside Chat', type: 'Democrat', category: 'special', power: 80, accuracy: 100, description: 'Speaks directly to the people. Burns with passion.', effect: { chance: 20, status: 'burn' } },
  penceFlat:        { name: 'Mother May I', type: 'Republican', category: 'status', power: 0, accuracy: 100, description: 'Asks for permission. Raises Sp.Def.', effect: { statBoost: { spd: 2 }, self: true } },
  penceFly:         { name: 'Fly on Head', type: 'Centrist', category: 'physical', power: 50, accuracy: 100, description: 'A fly lands. Somehow it hurts.', effect: { chance: 50, flinch: true } },
  desantisWoke:     { name: 'Anti-Woke Strike', type: 'Republican', category: 'special', power: 85, accuracy: 90, description: 'Bans wokeness for massive damage.', effect: null },
  desantisBan:      { name: 'Book Ban Bash', type: 'Authoritarian', category: 'physical', power: 70, accuracy: 100, description: 'Throws banned books at the opponent.', effect: null },
  newsom:           { name: 'California Dreamin\'', type: 'Democrat', category: 'special', power: 80, accuracy: 90, description: 'Attacks with the power of the fifth-largest economy.', effect: null },
  newsomRecall:     { name: 'Recall Reversal', type: 'Democrat', category: 'status', power: 0, accuracy: 100, description: 'Survives a recall. Boosts confidence.', effect: { statBoost: { spa: 1, spe: 1 }, self: true } },
  erdogan:          { name: 'Sultan\'s Decree', type: 'Authoritarian', category: 'special', power: 90, accuracy: 90, description: 'Rules with an iron decree.', effect: null },
  erdoganPurge:     { name: 'Political Purge', type: 'Authoritarian', category: 'status', power: 0, accuracy: 85, description: 'Purges opponents. Lowers all their stats.', effect: { statBoost: { atk: -1, def: -1, spe: -1 }, self: false } },
  chavez:           { name: 'Bolivarian Blast', type: 'Socialist', category: 'special', power: 90, accuracy: 85, description: 'A blast of revolutionary socialist energy.', effect: null },
  chavezNat:        { name: 'Nationalize!', type: 'Socialist', category: 'special', power: 75, accuracy: 100, description: 'Seizes the opponent\'s assets.', effect: { statBoost: { atk: -1, spa: -1 }, self: false } },
  obamacare:        { name: 'Healthcare Heal', type: 'Democrat', category: 'status', power: 0, accuracy: 100, description: 'The ACA provides healing.', effect: { heal: 0.4, self: true } },
};

// ── THE 50 POLITICIANS ──────────────────────────────────────────────────────
const POLITICIANS = [
  // ──────── MUST-HAVE: Required politicians ────────────
  {
    id: 'obama', name: 'Barack Obama', emoji: '🇺🇸', title: '44th President',
    types: ['Democrat', 'Centrist'],
    stats: { hp: 90, atk: 65, def: 80, spa: 120, spd: 95, spe: 100 },
    moves: [SIG.obamahameha, SIG.yesWeCan, TYPE_MOVES.blueWave, SIG.obamacare],
    flavor: 'Yes we can... destroy you in battle.',
  },
  {
    id: 'biden', name: 'Joe Biden', emoji: '🍦', title: '46th President',
    types: ['Democrat', 'Centrist'],
    stats: { hp: 100, atk: 60, def: 85, spa: 90, spd: 90, spe: 45 },
    moves: [SIG.bidenBlast, SIG.noMalarkey, TYPE_MOVES.socialProgram, TYPE_MOVES.compromise],
    flavor: 'Will you shut up, man? *blasts you*',
  },
  {
    id: 'trump', name: 'Donald Trump', emoji: '🍊', title: '45th & 47th President',
    types: ['Populist', 'Corporate'],
    stats: { hp: 95, atk: 110, def: 70, spa: 85, spd: 65, spe: 80 },
    moves: [SIG.deportTeleport, SIG.artOfDeal, TYPE_MOVES.crowdSurge, TYPE_MOVES.hostile],
    flavor: 'Nobody battles better than me. Believe me.',
  },
  {
    id: 'bush', name: 'George W. Bush', emoji: '🤠', title: '43rd President',
    types: ['Republican', 'Populist'],
    stats: { hp: 85, atk: 90, def: 80, spa: 65, spd: 75, spe: 70 },
    moves: [SIG.bushLeague, SIG.missionAccomp, TYPE_MOVES.gunLobby, TYPE_MOVES.rallyBase],
    flavor: 'Mission accomplished! ...right?',
  },
  {
    id: 'cheney', name: 'Dick Cheney', emoji: '🦆', title: 'VP & Shadow President',
    types: ['Republican', 'Corporate'],
    stats: { hp: 80, atk: 120, def: 90, spa: 75, spd: 70, spe: 50 },
    moves: [SIG.cheney_shot, SIG.darkEnergy, TYPE_MOVES.lobbyist, TYPE_MOVES.spikes],
    flavor: 'Accidentally devastating since 2001.',
  },
  {
    id: 'putin', name: 'Vladimir Putin', emoji: '🐻', title: 'President of Russia',
    types: ['Authoritarian', 'Populist'],
    stats: { hp: 100, atk: 115, def: 95, spa: 90, spd: 85, spe: 75 },
    moves: [SIG.putinPunch, SIG.novichok, SIG.poopootin, TYPE_MOVES.ironCurtain],
    flavor: 'Rides bears. Punches democracy.',
  },
  {
    id: 'hitler', name: 'Adolf Hitler', emoji: '💀', title: 'History\'s Villain',
    types: ['Authoritarian'],
    stats: { hp: 85, atk: 130, def: 60, spa: 110, spd: 50, spe: 95 },
    moves: [SIG.hitlerBlitz, SIG.naziPropaganda, TYPE_MOVES.executiveOrder, TYPE_MOVES.secretPolice],
    flavor: 'The final boss of history. Pure evil.',
  },
  // ──────── MORE US POLITICIANS ────────────
  {
    id: 'bernie', name: 'Bernie Sanders', emoji: '🧤', title: 'Senator from Vermont',
    types: ['Socialist', 'Populist'],
    stats: { hp: 95, atk: 60, def: 75, spa: 115, spd: 85, spe: 55 },
    moves: [SIG.bernBurn, SIG.wallStreetBust, TYPE_MOVES.redistribute, TYPE_MOVES.rallyBase],
    flavor: 'I am once again asking you to take damage.',
  },
  {
    id: 'hillary', name: 'Hillary Clinton', emoji: '👔', title: 'Secretary of State',
    types: ['Democrat', 'Corporate'],
    stats: { hp: 85, atk: 55, def: 80, spa: 110, spd: 90, spe: 75 },
    moves: [SIG.hillaryMail, SIG.deleteEmails, TYPE_MOVES.factCheck, TYPE_MOVES.lobbyist],
    flavor: 'Pokémon? Like with a cloth?',
  },
  {
    id: 'aoc', name: 'Alexandria Ocasio-Cortez', emoji: '💪', title: 'The Squad',
    types: ['Socialist', 'Green'],
    stats: { hp: 75, atk: 55, def: 60, spa: 120, spd: 70, spe: 110 },
    moves: [SIG.aocClap, SIG.greenNewDeal, TYPE_MOVES.classWar, TYPE_MOVES.solarBeam],
    flavor: 'Yaaaas queen, now take this L.',
  },
  {
    id: 'pelosi', name: 'Nancy Pelosi', emoji: '👏', title: 'Speaker of the House',
    types: ['Democrat', 'Corporate'],
    stats: { hp: 80, atk: 60, def: 85, spa: 100, spd: 95, spe: 65 },
    moves: [SIG.pelosi_clap, SIG.pelosiRip, TYPE_MOVES.cancelCulture, TYPE_MOVES.goldenPara],
    flavor: 'Claps sarcastically. It\'s super effective.',
  },
  {
    id: 'tedcruz', name: 'Ted Cruz', emoji: '✈️', title: 'Senator from Texas',
    types: ['Republican', 'Populist'],
    stats: { hp: 85, atk: 70, def: 65, spa: 90, spd: 70, spe: 60 },
    moves: [SIG.tedCruzFlee, SIG.zodiacKill, TYPE_MOVES.filibuster, TYPE_MOVES.taxCut],
    flavor: 'Definitely not the Zodiac Killer. Definitely.',
  },
  {
    id: 'mcconnell', name: 'Mitch McConnell', emoji: '🐢', title: 'Senate Minority Leader',
    types: ['Republican', 'Corporate'],
    stats: { hp: 95, atk: 45, def: 120, spa: 70, spd: 115, spe: 30 },
    moves: [SIG.mcconnellShell, SIG.mcconnellBlock, TYPE_MOVES.filibuster, TYPE_MOVES.stealthRock],
    flavor: 'The turtle that blocks everything.',
  },
  {
    id: 'kamala', name: 'Kamala Harris', emoji: '⚖️', title: '49th Vice President',
    types: ['Democrat', 'Centrist'],
    stats: { hp: 80, atk: 60, def: 75, spa: 105, spd: 85, spe: 90 },
    moves: [SIG.kamalaLaugh, SIG.prosecutorSlam, TYPE_MOVES.blueWave, TYPE_MOVES.factCheck],
    flavor: 'Prosecuting her way through the bracket.',
  },
  {
    id: 'romney', name: 'Mitt Romney', emoji: '🏦', title: 'Senator from Utah',
    types: ['Republican', 'Centrist'],
    stats: { hp: 85, atk: 70, def: 85, spa: 80, spd: 90, spe: 70 },
    moves: [SIG.mittRomney, SIG.romneyFlip, TYPE_MOVES.taxCut, TYPE_MOVES.compromise],
    flavor: 'Has binders full of battle strategies.',
  },
  {
    id: 'reagan', name: 'Ronald Reagan', emoji: '⭐', title: '40th President',
    types: ['Republican', 'Corporate'],
    stats: { hp: 85, atk: 80, def: 75, spa: 100, spd: 80, spe: 85 },
    moves: [SIG.reaganomics, SIG.tearDownWall, TYPE_MOVES.taxCut, TYPE_MOVES.gunLobby],
    flavor: 'Mr. Gorbachev, take this damage!',
  },
  {
    id: 'musk', name: 'Elon Musk', emoji: '🚀', title: 'Techno King',
    types: ['Libertarian', 'Corporate'],
    stats: { hp: 80, atk: 70, def: 55, spa: 115, spd: 60, spe: 105 },
    moves: [SIG.muskTweet, SIG.muskRocket, TYPE_MOVES.freeMkt, TYPE_MOVES.deregulate],
    flavor: 'The algorithm will decide your fate.',
  },
  {
    id: 'pence', name: 'Mike Pence', emoji: '🪰', title: '48th Vice President',
    types: ['Republican', 'Centrist'],
    stats: { hp: 80, atk: 55, def: 90, spa: 65, spd: 100, spe: 50 },
    moves: [SIG.penceFlat, SIG.penceFly, TYPE_MOVES.filibuster, TYPE_MOVES.compromise],
    flavor: 'The fly was the real MVP.',
  },
  {
    id: 'desantis', name: 'Ron DeSantis', emoji: '🐊', title: 'Governor of Florida',
    types: ['Republican', 'Authoritarian'],
    stats: { hp: 85, atk: 90, def: 80, spa: 85, spd: 70, spe: 65 },
    moves: [SIG.desantisWoke, SIG.desantisBan, TYPE_MOVES.redWave, TYPE_MOVES.executiveOrder],
    flavor: 'Florida Man becomes Florida Governor.',
  },
  {
    id: 'newsom', name: 'Gavin Newsom', emoji: '🌉', title: 'Governor of California',
    types: ['Democrat', 'Corporate'],
    stats: { hp: 80, atk: 60, def: 70, spa: 95, spd: 80, spe: 85 },
    moves: [SIG.newsom, SIG.newsomRecall, TYPE_MOVES.blueWave, TYPE_MOVES.socialProgram],
    flavor: 'Hair gel is his secret weapon.',
  },
  // ──────── WORLD LEADERS ────────────
  {
    id: 'thatcher', name: 'Margaret Thatcher', emoji: '👑', title: 'Iron Lady',
    types: ['Republican', 'Corporate'],
    stats: { hp: 80, atk: 85, def: 90, spa: 95, spd: 85, spe: 70 },
    moves: [SIG.thatcherSmash, SIG.thatcherCrush, TYPE_MOVES.taxCut, TYPE_MOVES.lobbyist],
    flavor: 'The lady\'s not for turning... or losing.',
  },
  {
    id: 'zelensky', name: 'Volodymyr Zelensky', emoji: '🇺🇦', title: 'President of Ukraine',
    types: ['Revolutionary', 'Populist'],
    stats: { hp: 90, atk: 95, def: 85, spa: 75, spd: 80, spe: 90 },
    moves: [SIG.zelensky, SIG.zelenskyInspire, TYPE_MOVES.uprising, TYPE_MOVES.crowdSurge],
    flavor: 'Needs ammo, not a ride. Or Pokémon.',
  },
  {
    id: 'jinping', name: 'Xi Jinping', emoji: '🐝', title: 'President of China',
    types: ['Authoritarian', 'Corporate'],
    stats: { hp: 100, atk: 90, def: 100, spa: 95, spd: 90, spe: 60 },
    moves: [SIG.jinpingGrip, SIG.jinpingCensor, TYPE_MOVES.executiveOrder, TYPE_MOVES.ironCurtain],
    flavor: 'Definitely not Winnie the Pooh.',
  },
  {
    id: 'kim', name: 'Kim Jong-un', emoji: '🚀', title: 'Supreme Leader',
    types: ['Authoritarian'],
    stats: { hp: 90, atk: 100, def: 70, spa: 100, spd: 65, spe: 55 },
    moves: [SIG.kimNuke, SIG.kimParade, TYPE_MOVES.propaganda, TYPE_MOVES.secretPolice],
    flavor: 'Has nukes. May or may not work.',
  },
  {
    id: 'merkel', name: 'Angela Merkel', emoji: '🇩🇪', title: 'Chancellor of Germany',
    types: ['Centrist', 'Corporate'],
    stats: { hp: 90, atk: 55, def: 95, spa: 95, spd: 100, spe: 60 },
    moves: [SIG.merkelStare, SIG.merkelScience, TYPE_MOVES.compromise, TYPE_MOVES.bipartisan],
    flavor: 'Wissenschaft über alles.',
  },
  {
    id: 'trudeau', name: 'Justin Trudeau', emoji: '🍁', title: 'PM of Canada',
    types: ['Democrat', 'Centrist'],
    stats: { hp: 80, atk: 80, def: 70, spa: 75, spd: 75, spe: 85 },
    moves: [SIG.trudeau, SIG.trudeauBox, TYPE_MOVES.blueWave, TYPE_MOVES.socialProgram],
    flavor: 'Sorry, not sorry for beating you.',
  },
  {
    id: 'boris', name: 'Boris Johnson', emoji: '💇', title: 'PM of the UK',
    types: ['Populist', 'Republican'],
    stats: { hp: 90, atk: 85, def: 65, spa: 80, spd: 65, spe: 75 },
    moves: [SIG.borisBuffoon, SIG.borisBrexit, TYPE_MOVES.crowdSurge, TYPE_MOVES.rallyBase],
    flavor: 'The hair is where the power resides.',
  },
  {
    id: 'pope', name: 'Pope Francis', emoji: '⛪', title: 'Head of the Vatican',
    types: ['Centrist', 'Green'],
    stats: { hp: 100, atk: 40, def: 90, spa: 85, spd: 110, spe: 45 },
    moves: [SIG.popeBlessing, SIG.popeSmite, TYPE_MOVES.recycle, TYPE_MOVES.treeHug],
    flavor: 'Forgives you. Then smites you.',
  },
  {
    id: 'gandhi', name: 'Mahatma Gandhi', emoji: '🕊️', title: 'Father of India',
    types: ['Green', 'Revolutionary'],
    stats: { hp: 85, atk: 40, def: 100, spa: 80, spd: 120, spe: 50 },
    moves: [SIG.gandhi, SIG.gandhiMarch, TYPE_MOVES.solarBeam, TYPE_MOVES.recycle],
    flavor: 'Be the change. Then body-slam.',
  },
  {
    id: 'mandela', name: 'Nelson Mandela', emoji: '✊', title: 'President of South Africa',
    types: ['Revolutionary', 'Centrist'],
    stats: { hp: 100, atk: 70, def: 100, spa: 85, spd: 100, spe: 45 },
    moves: [SIG.mandela, SIG.mandelaUnite, TYPE_MOVES.uprising, TYPE_MOVES.bipartisan],
    flavor: 'It always seems impossible until it\'s done.',
  },
  {
    id: 'lincoln', name: 'Abraham Lincoln', emoji: '🎩', title: '16th President',
    types: ['Republican', 'Revolutionary'],
    stats: { hp: 95, atk: 100, def: 90, spa: 85, spd: 85, spe: 60 },
    moves: [SIG.lincolnAxe, SIG.emancipate, TYPE_MOVES.redWave, TYPE_MOVES.uprising],
    flavor: 'Four score and seven hits ago...',
  },
  {
    id: 'fdr', name: 'Franklin D. Roosevelt', emoji: '🦅', title: '32nd President',
    types: ['Democrat', 'Socialist'],
    stats: { hp: 110, atk: 60, def: 90, spa: 100, spd: 95, spe: 45 },
    moves: [SIG.fdrDeal, SIG.fdrFireside, TYPE_MOVES.blueWave, TYPE_MOVES.redistribute],
    flavor: 'The only thing to fear is this moveset.',
  },
  {
    id: 'jfk', name: 'John F. Kennedy', emoji: '🌙', title: '35th President',
    types: ['Democrat', 'Centrist'],
    stats: { hp: 80, atk: 70, def: 70, spa: 100, spd: 80, spe: 100 },
    moves: [SIG.jfkMoon, SIG.jfkCharm, TYPE_MOVES.blueWave, TYPE_MOVES.bipartisan],
    flavor: 'Ask not what your team can do for you.',
  },
  {
    id: 'nixon', name: 'Richard Nixon', emoji: '✌️', title: '37th President',
    types: ['Republican', 'Authoritarian'],
    stats: { hp: 85, atk: 75, def: 80, spa: 90, spd: 75, spe: 70 },
    moves: [SIG.nixonTrick, SIG.watergate, TYPE_MOVES.secretPolice, TYPE_MOVES.spikes],
    flavor: 'I am not a crook... but I am a battler.',
  },
  {
    id: 'gore', name: 'Al Gore', emoji: '🌍', title: 'Almost President',
    types: ['Green', 'Democrat'],
    stats: { hp: 80, atk: 55, def: 75, spa: 100, spd: 85, spe: 65 },
    moves: [SIG.goreInternet, SIG.inconvenientTruth, TYPE_MOVES.solarBeam, TYPE_MOVES.recycle],
    flavor: 'Invented the internet AND this beating.',
  },
  {
    id: 'che', name: 'Che Guevara', emoji: '🔴', title: 'Revolutionary Icon',
    types: ['Revolutionary', 'Socialist'],
    stats: { hp: 80, atk: 110, def: 65, spa: 80, spd: 60, spe: 100 },
    moves: [SIG.cheGuevara, SIG.guerrilla, TYPE_MOVES.classWar, TYPE_MOVES.uprising],
    flavor: 'On a t-shirt near you. Also here to fight.',
  },
  {
    id: 'erdogan', name: 'Recep Erdoğan', emoji: '🇹🇷', title: 'President of Turkey',
    types: ['Authoritarian', 'Populist'],
    stats: { hp: 90, atk: 85, def: 80, spa: 85, spd: 75, spe: 65 },
    moves: [SIG.erdogan, SIG.erdoganPurge, TYPE_MOVES.executiveOrder, TYPE_MOVES.crowdSurge],
    flavor: 'Democracy is a train you ride until your stop.',
  },
  {
    id: 'chavez', name: 'Hugo Chávez', emoji: '🛢️', title: 'President of Venezuela',
    types: ['Socialist', 'Authoritarian'],
    stats: { hp: 90, atk: 75, def: 70, spa: 95, spd: 70, spe: 65 },
    moves: [SIG.chavez, SIG.chavezNat, TYPE_MOVES.redistribute, TYPE_MOVES.propaganda],
    flavor: 'Nationalizes your HP bar.',
  },
  // ──────── MORE US/WORLD ────────────
  {
    id: 'warren', name: 'Elizabeth Warren', emoji: '📋', title: 'Senator from MA',
    types: ['Democrat', 'Socialist'],
    stats: { hp: 80, atk: 50, def: 75, spa: 110, spd: 85, spe: 70 },
    moves: [TYPE_MOVES.factCheck, TYPE_MOVES.redistribute, TYPE_MOVES.cancelCulture, TYPE_MOVES.socialProgram],
    flavor: 'Has a plan for that. And that. And that.',
  },
  {
    id: 'rand', name: 'Rand Paul', emoji: '⚡', title: 'Senator from KY',
    types: ['Libertarian', 'Republican'],
    stats: { hp: 75, atk: 65, def: 60, spa: 90, spd: 75, spe: 95 },
    moves: [TYPE_MOVES.freeMkt, TYPE_MOVES.deregulate, TYPE_MOVES.dontTread, TYPE_MOVES.filibuster],
    flavor: 'The free market will decide the winner.',
  },
  {
    id: 'cortez', name: 'Fidel Castro', emoji: '🎖️', title: 'Cuban Revolutionary',
    types: ['Revolutionary', 'Authoritarian'],
    stats: { hp: 95, atk: 85, def: 80, spa: 85, spd: 75, spe: 55 },
    moves: [TYPE_MOVES.uprising, TYPE_MOVES.propaganda, TYPE_MOVES.executiveOrder, SIG.guerrilla],
    flavor: 'The revolution will not be televised.',
  },
  {
    id: 'modi', name: 'Narendra Modi', emoji: '🇮🇳', title: 'PM of India',
    types: ['Populist', 'Authoritarian'],
    stats: { hp: 90, atk: 80, def: 85, spa: 85, spd: 80, spe: 65 },
    moves: [TYPE_MOVES.crowdSurge, TYPE_MOVES.rallyBase, TYPE_MOVES.executiveOrder, TYPE_MOVES.propaganda],
    flavor: 'The world\'s most followed leader attacks.',
  },
  {
    id: 'macron', name: 'Emmanuel Macron', emoji: '🇫🇷', title: 'President of France',
    types: ['Centrist', 'Corporate'],
    stats: { hp: 80, atk: 65, def: 75, spa: 90, spd: 80, spe: 90 },
    moves: [TYPE_MOVES.bipartisan, TYPE_MOVES.lobbyist, TYPE_MOVES.compromise, TYPE_MOVES.moderateSlap],
    flavor: 'En marche! Right into your HP bar.',
  },
  {
    id: 'bezos', name: 'Jeff Bezos', emoji: '📦', title: 'Overlord of Amazon',
    types: ['Corporate', 'Libertarian'],
    stats: { hp: 85, atk: 65, def: 70, spa: 110, spd: 75, spe: 80 },
    moves: [TYPE_MOVES.hostile, TYPE_MOVES.lobbyist, TYPE_MOVES.freeMkt, TYPE_MOVES.stickyWeb],
    flavor: 'Your order of pain has been dispatched.',
  },
  {
    id: 'zuckerberg', name: 'Mark Zuckerberg', emoji: '🤖', title: 'Meta Overlord',
    types: ['Corporate', 'Centrist'],
    stats: { hp: 75, atk: 60, def: 65, spa: 100, spd: 70, spe: 95 },
    moves: [TYPE_MOVES.lobbyist, TYPE_MOVES.stickyWeb, TYPE_MOVES.bipartisan, TYPE_MOVES.goldenPara],
    flavor: 'Your data IS the attack.',
  },
  {
    id: 'stalin', name: 'Joseph Stalin', emoji: '⚒️', title: 'Soviet Dictator',
    types: ['Authoritarian', 'Socialist'],
    stats: { hp: 110, atk: 120, def: 90, spa: 80, spd: 70, spe: 50 },
    moves: [TYPE_MOVES.secretPolice, TYPE_MOVES.ironCurtain, TYPE_MOVES.executiveOrder, TYPE_MOVES.propaganda],
    flavor: 'One fainting is a tragedy. A million is a statistic.',
  },
  {
    id: 'churchill', name: 'Winston Churchill', emoji: '🎩', title: 'PM of the UK',
    types: ['Republican', 'Populist'],
    stats: { hp: 100, atk: 85, def: 90, spa: 90, spd: 80, spe: 55 },
    moves: [TYPE_MOVES.gunLobby, TYPE_MOVES.rallyBase, TYPE_MOVES.redWave, TYPE_MOVES.stealthRock],
    flavor: 'We shall fight on the battle screens!',
  },
  {
    id: 'cleopatra', name: 'Cleopatra', emoji: '🐍', title: 'Queen of Egypt',
    types: ['Authoritarian', 'Corporate'],
    stats: { hp: 80, atk: 60, def: 70, spa: 115, spd: 80, spe: 90 },
    moves: [TYPE_MOVES.executiveOrder, TYPE_MOVES.lobbyist, TYPE_MOVES.goldenPara, TYPE_MOVES.propaganda],
    flavor: 'The original girlboss. Now in battle form.',
  },
  {
    id: 'caesar', name: 'Julius Caesar', emoji: '🗡️', title: 'Dictator of Rome',
    types: ['Authoritarian', 'Populist'],
    stats: { hp: 85, atk: 110, def: 70, spa: 80, spd: 65, spe: 95 },
    moves: [TYPE_MOVES.executiveOrder, TYPE_MOVES.crowdSurge, TYPE_MOVES.secretPolice, TYPE_MOVES.pitchfork],
    flavor: 'Et tu, opponent? *stabs back*',
  },
  {
    id: 'mlk', name: 'Martin Luther King Jr.', emoji: '✊', title: 'Civil Rights Leader',
    types: ['Revolutionary', 'Green'],
    stats: { hp: 90, atk: 50, def: 85, spa: 110, spd: 105, spe: 60 },
    moves: [TYPE_MOVES.uprising, TYPE_MOVES.solarBeam, SIG.gandhi, TYPE_MOVES.recycle],
    flavor: 'I have a dream... of winning this battle.',
  },
];

module.exports = POLITICIANS;
