// ─── Tool Definitions — 65 tools total ────────────────────────────────────────
const TOOLS = [
  // ══ TEXT TOOLS ══════════════════════════════════════════════════════════════
  { id:'ai-detector',          name:'AI Content Detector',        description:'Analyse any text with 15 statistical and linguistic signals to detect if it was written by an AI model or a human — no external API, fully private', category:'text',    icon:'🔍', trending:true,  premium:false, enabled:true, tags:['ai detector','chatgpt detect','ai check','originality','gptzero'] },
  { id:'ai-humanizer',         name:'AI Text Humanizer',          description:'Transform robotic AI-generated text into natural, human-sounding prose using 50+ linguistic rules including burstiness injection, perplexity enhancement, and personal voice', category:'text',    icon:'🤖', trending:true,  premium:false, enabled:true, tags:['ai','humanize','rewrite','chatgpt','bypass'] },
  { id:'paraphraser',          name:'Paraphrasing Tool',          description:'Rewrite any paragraph in your own words using synonym replacement, clause reordering, and structural variation — get up to 3 unique variations', category:'text',    icon:'✏️', trending:true,  premium:false, enabled:true, tags:['paraphrase','rewrite','rephrase'] },
  { id:'summarizer',           name:'Text Summarizer',            description:'Condense long articles, essays or documents into concise bullet-point or paragraph summaries using keyword scoring and sentence importance analysis', category:'text',    icon:'📝', trending:false, premium:false, enabled:true, tags:['summarize','condense','tldr'] },
  { id:'grammar-fixer',        name:'Grammar Fixer',              description:'Automatically detect and fix grammar, spelling, punctuation and sentence structure errors using rule-based correction — no account required', category:'text',    icon:'✅', trending:true,  premium:false, enabled:true, tags:['grammar','spelling','proofread'] },
  { id:'word-counter',         name:'Word Counter',               description:'Count words, characters (with and without spaces), sentences, paragraphs, unique words and estimated reading time instantly as you type', category:'text',    icon:'🔢', trending:false, premium:false, enabled:true, tags:['word count','character count','stats'] },
  { id:'case-converter',       name:'Case Converter',             description:'Convert text between UPPER CASE, lower case, Title Case, Sentence case, camelCase, PascalCase, snake_case, kebab-case and more in one click', category:'text',    icon:'Aa', trending:false, premium:false, enabled:true, tags:['uppercase','lowercase','title case','camelcase'] },
  { id:'tone-analyzer',        name:'Tone Analyzer',              description:'Detect the overall sentiment, formality level, dominant emotions (joy, anger, sadness, surprise), and communication style of any text passage', category:'text',    icon:'🎭', trending:true,  premium:false, enabled:true, tags:['tone','sentiment','emotion','analysis'] },
  { id:'sentence-expander',    name:'Sentence Expander',          description:'Expand short, sparse sentences into richer, more detailed prose by injecting contextual elaborations, supporting clauses, and descriptive language', category:'text',    icon:'📈', trending:true,  premium:false, enabled:true, tags:['expand','elaborate','writing','detail'] },
  { id:'text-cleaner',         name:'Text Cleaner',               description:'Remove duplicate lines, fix irregular spacing, strip HTML tags, normalize smart quotes, fix encoding artifacts, and clean up messy copy-pasted text', category:'text',    icon:'🧹', trending:true,  premium:false, enabled:true, tags:['clean','format','html','spacing','normalize'] },
  { id:'bullet-points',        name:'Bullet Point Converter',     description:'Convert any flowing prose into clean, scannable bullet points with custom styles (•, -, ✓, ▶) and configurable maximum item count', category:'text',    icon:'📋', trending:true,  premium:false, enabled:true, tags:['bullet points','list','structure','convert'] },
  { id:'cliche-detector',      name:'Cliché Detector',            description:'Identify overused phrases, tired idioms, business jargon, and AI writing patterns in your text — with optional auto-replacement suggestions', category:'text',    icon:'🚫', trending:true,  premium:false, enabled:true, tags:['cliche','jargon','originality','writing'] },
  { id:'markdown-previewer',   name:'Markdown Previewer',         description:'Write Markdown and see a live rendered preview side by side',                          category:'text',    icon:'📄', trending:true,  premium:false, enabled:true, tags:['markdown','preview','live','editor'] },
  { id:'emoji-picker',         name:'Emoji Picker',               description:'Browse, search, and copy emojis organized by category with one click',                category:'text',    icon:'😀', trending:true,  premium:false, enabled:true, tags:['emoji','copy','picker','symbols'] },
  { id:'lorem-ipsum',          name:'Lorem Ipsum Generator',      description:'Generate placeholder text by paragraphs, sentences, or words',                        category:'text',    icon:'📃', trending:false, premium:false, enabled:true, tags:['lorem','placeholder','dummy'] },
  { id:'word-frequency',       name:'Word Frequency Analyzer',    description:'Find the most common words in any text with visual frequency bars',                   category:'text',    icon:'📊', trending:false, premium:false, enabled:true, tags:['word','frequency','analyze'] },
  { id:'text-diff',            name:'Text Diff Checker',          description:'Compare two texts side by side and highlight all additions and removals',              category:'text',    icon:'🔍', trending:true,  premium:false, enabled:true, tags:['diff','compare','changes'] },
  { id:'readability-checker',  name:'Readability Checker',        description:'Get Flesch score, grade level, and estimated reading time for any text',               category:'text',    icon:'📖', trending:false, premium:false, enabled:true, tags:['readability','flesch','grade'] },
  { id:'text-to-speech',       name:'Text to Speech',             description:'Convert any text into spoken audio in multiple voices and languages',                  category:'text',    icon:'🔊', trending:true,  premium:false, enabled:true, tags:['tts','speech','audio','voice'] },
  { id:'hashtag-generator',    name:'Hashtag Generator',          description:'Generate relevant hashtags for Instagram, Twitter, LinkedIn, and TikTok',              category:'text',    icon:'#️⃣', trending:true,  premium:false, enabled:true, tags:['hashtag','social media','instagram'] },
  { id:'email-subject-generator',name:'Email Subject Generator',  description:'Create compelling email subject lines that get opened based on your content',         category:'text',    icon:'📧', trending:false, premium:false, enabled:true, tags:['email','subject line','marketing'] },
  { id:'plagiarism-highlighter',name:'Plagiarism Highlighter',    description:'Highlight repeated phrases and near-duplicate sentences within a single text',        category:'text',    icon:'🔎', trending:false, premium:false, enabled:true, tags:['plagiarism','duplicate','originality'] },
  { id:'sentence-rewriter',    name:'Sentence Rewriter',          description:'Rewrite any sentence 5 different ways — formal, casual, concise, and more',           category:'text',    icon:'🔄', trending:false, premium:false, enabled:true, tags:['rewrite','sentence','rephrase'] },
  { id:'active-voice-converter',name:'Active Voice Converter',    description:'Automatically convert passive voice sentences to active voice for stronger writing',   category:'text',    icon:'💪', trending:false, premium:false, enabled:true, tags:['active voice','passive voice','grammar'] },
  { id:'character-counter',    name:'Character Limit Checker',    description:'Check your text against Twitter, Instagram, LinkedIn, SMS and other platform limits',  category:'text',    icon:'📏', trending:false, premium:false, enabled:true, tags:['character','limit','twitter','instagram'] },
  { id:'markdown-to-html',     name:'Markdown to HTML',           description:'Convert Markdown text to clean, semantic HTML code instantly',                        category:'text',    icon:'🌐', trending:true,  premium:false, enabled:true, tags:['markdown','html','convert','code'] },

  // ══ MEDIA TOOLS ═════════════════════════════════════════════════════════════
  { id:'image-converter',      name:'Image Converter',            description:'Convert images between PNG, JPG, WebP, GIF, and more formats in seconds',             category:'media',   icon:'🖼️', trending:true,  premium:false, enabled:true, tags:['image','convert','png','jpg'] },
  { id:'image-resizer',        name:'Image Resizer',              description:'Resize and compress images to any dimension with quality control',                    category:'media',   icon:'📐', trending:false, premium:false, enabled:true, tags:['resize','compress','image'] },
  { id:'yt-thumbnail',         name:'YouTube Thumbnail Downloader',description:'Download thumbnails from any YouTube video in HD, SD, and max quality',              category:'media',   icon:'▶️', trending:true,  premium:false, enabled:true, tags:['youtube','thumbnail','download'] },
  { id:'qr-generator',         name:'QR Code Generator',          description:'Generate QR codes for URLs, text, emails, Wi-Fi, and more — downloadable as PNG',     category:'media',   icon:'⬛', trending:true,  premium:false, enabled:true, tags:['qr code','generate','barcode'] },
  { id:'color-palette',        name:'Color Palette Generator',    description:'Generate beautiful color palettes from any seed color with HEX, RGB, and HSL values', category:'media',   icon:'🎨', trending:false, premium:false, enabled:true, tags:['color','palette','design','hex'] },
  { id:'base64',               name:'Base64 Encoder / Decoder',   description:'Encode and decode text or files to and from Base64 format instantly',                 category:'media',   icon:'🔤', trending:false, premium:false, enabled:true, tags:['base64','encode','decode'] },
  { id:'image-to-text',        name:'Image to Text (OCR)',         description:'Extract readable text from images, screenshots, and scanned documents',               category:'media',   icon:'👁️', trending:true,  premium:false, enabled:true, tags:['ocr','image to text','extract'] },
  { id:'color-picker',         name:'Color Picker & Converter',   description:'Pick any color and instantly get its HEX, RGB, HSL, and CMYK values',                 category:'media',   icon:'🎯', trending:false, premium:false, enabled:true, tags:['color picker','hex','rgb','hsl'] },
  { id:'favicon-generator',    name:'Favicon Generator',          description:'Create a favicon from any image or text — download in all required sizes',             category:'media',   icon:'⭐', trending:false, premium:false, enabled:true, tags:['favicon','icon','website'] },
  { id:'gif-maker',            name:'GIF Maker',                  description:'Create animated GIFs from a series of images or by extracting frames',                category:'media',   icon:'🎞️', trending:true,  premium:false, enabled:true, tags:['gif','animate','image','frames'] },
  { id:'screenshot-resizer',   name:'Screenshot Resizer',         description:'Resize screenshots for social media, App Store, Play Store, and more',                category:'media',   icon:'📱', trending:false, premium:false, enabled:true, tags:['screenshot','resize','social media'] },
  { id:'gradient-generator',   name:'CSS Gradient Generator',     description:'Create beautiful CSS linear and radial gradients with live preview and code copy',     category:'media',   icon:'🌈', trending:true,  premium:false, enabled:true, tags:['gradient','css','design','color'] },

  // ══ UTILITY TOOLS ═══════════════════════════════════════════════════════════
  { id:'password-generator',   name:'Password Generator',         description:'Generate strong, secure passwords with custom length, symbols, and rules',             category:'utility', icon:'🔐', trending:true,  premium:false, enabled:true, tags:['password','security','generate'] },
  { id:'timestamp-converter',  name:'Timestamp Converter',        description:'Convert between Unix timestamps and human-readable dates in any timezone',            category:'utility', icon:'🕐', trending:false, premium:false, enabled:true, tags:['timestamp','unix','date','convert'] },
  { id:'json-formatter',       name:'JSON Formatter',             description:'Format, validate, and minify JSON data with syntax highlighting and error detection',  category:'utility', icon:'{ }',trending:true,  premium:false, enabled:true, tags:['json','format','validate'] },
  { id:'name-generator',       name:'Random Name Generator',      description:'Generate random names for characters, businesses, projects, and usernames',            category:'utility', icon:'👤', trending:false, premium:false, enabled:true, tags:['name','random','generate'] },
  { id:'unit-converter',       name:'Unit Converter',             description:'Convert between length, weight, temperature, volume, speed, and more units',           category:'utility', icon:'⚖️', trending:false, premium:false, enabled:true, tags:['unit','convert','measurement'] },
  { id:'calculator',           name:'Scientific Calculator',      description:'Fast, clean calculator with history, scientific functions, and expression evaluator',  category:'utility', icon:'🧮', trending:false, premium:false, enabled:true, tags:['calculate','math','scientific'] },
  { id:'binary-converter',     name:'Text ↔ Binary Converter',    description:'Convert text to binary code and binary back to readable text instantly',               category:'utility', icon:'01', trending:false, premium:false, enabled:true, tags:['binary','text','convert'] },
  { id:'url-encoder',          name:'URL Encoder / Decoder',      description:'Encode special characters in URLs or decode percent-encoded URLs',                    category:'utility', icon:'🔗', trending:false, premium:false, enabled:true, tags:['url','encode','decode'] },
  { id:'ip-lookup',            name:'IP Address Lookup',          description:'Look up any IP address to find its location, ISP, timezone, and more',                category:'utility', icon:'🌐', trending:false, premium:false, enabled:true, tags:['ip address','lookup','geolocation'] },
  { id:'hash-generator',       name:'Hash Generator',             description:'Generate MD5, SHA-1, SHA-256, SHA-512 hashes for any text or file',                   category:'utility', icon:'#️⃣', trending:false, premium:false, enabled:true, tags:['hash','md5','sha256','checksum'] },
  { id:'regex-tester',         name:'Regex Tester',               description:'Test regular expressions against sample text with live match highlighting',            category:'utility', icon:'⚡', trending:true,  premium:false, enabled:true, tags:['regex','regular expression','test'] },
  { id:'css-minifier',         name:'CSS Minifier',               description:'Minify CSS code to reduce file size and improve page load speed',                      category:'utility', icon:'🎨', trending:false, premium:false, enabled:true, tags:['css','minify','compress'] },
  { id:'html-minifier',        name:'HTML Minifier',              description:'Strip whitespace and comments from HTML to reduce page size instantly',                category:'utility', icon:'🏗️', trending:false, premium:false, enabled:true, tags:['html','minify','compress'] },
  { id:'js-minifier',          name:'JavaScript Minifier',        description:'Minify JavaScript code to shrink file size without breaking functionality',            category:'utility', icon:'⚙️', trending:false, premium:false, enabled:true, tags:['javascript','minify','compress'] },
  { id:'color-contrast',       name:'Color Contrast Checker',     description:'Check WCAG color contrast ratios for accessibility compliance (AA and AAA)',           category:'utility', icon:'♿', trending:false, premium:false, enabled:true, tags:['color','contrast','accessibility','wcag'] },
  { id:'currency-converter',   name:'Currency Converter',         description:'Convert between world currencies with up-to-date exchange rates',                     category:'utility', icon:'💱', trending:true,  premium:false, enabled:true, tags:['currency','exchange rate','money'] },
  { id:'age-calculator',       name:'Age Calculator',             description:'Calculate exact age in years, months, days, hours, and minutes from a birthdate',     category:'utility', icon:'🎂', trending:false, premium:false, enabled:true, tags:['age','birthday','date'] },
  { id:'percentage-calculator',name:'Percentage Calculator',      description:'Calculate percentages, percent change, percent of totals, and reverse percentages',    category:'utility', icon:'%',  trending:false, premium:false, enabled:true, tags:['percentage','percent','math'] },
  { id:'bmi-calculator',       name:'BMI Calculator',             description:'Calculate Body Mass Index with metric and imperial support and healthy range guide',   category:'utility', icon:'⚕️', trending:false, premium:false, enabled:true, tags:['bmi','body mass','health','weight'] },
  { id:'timezone-converter',   name:'Time Zone Converter',        description:'Convert times between any world time zones — great for scheduling meetings',           category:'utility', icon:'🌍', trending:false, premium:false, enabled:true, tags:['timezone','time','world clock'] },
  { id:'uuid-generator',       name:'UUID Generator',             description:'Generate UUIDs (v1, v4) and NanoIDs for use in databases and applications',            category:'utility', icon:'🆔', trending:false, premium:false, enabled:true, tags:['uuid','guid','nanoid','unique id'] },
  { id:'number-to-words',      name:'Number to Words',            description:'Convert any number into its written English word form (e.g. 1,234 → one thousand…)',  category:'utility', icon:'🔢', trending:false, premium:false, enabled:true, tags:['number','words','convert','spell'] },
  { id:'random-picker',        name:'Random Picker / Dice Roller', description:'Pick a random item from a list, roll dice, flip a coin, or draw random numbers',    category:'utility', icon:'🎲', trending:false, premium:false, enabled:true, tags:['random','pick','dice','coin'] },
  { id:'slug-generator',       name:'URL Slug Generator',         description:'Convert any title or phrase into a clean, SEO-friendly URL slug',                     category:'utility', icon:'🔗', trending:false, premium:false, enabled:true, tags:['slug','url','seo','permalink'] },
  { id:'morse-code',           name:'Morse Code Translator',      description:'Translate text to Morse code and Morse code back to text instantly',                  category:'utility', icon:'📡', trending:false, premium:false, enabled:true, tags:['morse','code','translate','signal'] },
  { id:'csv-to-json',          name:'CSV to JSON Converter',      description:'Convert CSV data to JSON format instantly with custom delimiter support',              category:'utility', icon:'📂', trending:true,  premium:false, enabled:true, tags:['csv','json','convert','data'] },
  { id:'pomodoro-timer',       name:'Pomodoro Timer',             description:'Boost productivity with a customizable Pomodoro focus timer and break scheduler',     category:'utility', icon:'⏱️', trending:true,  premium:false, enabled:true, tags:['pomodoro','timer','focus','productivity'] },
  { id:'typing-test',          name:'Typing Speed Test',          description:'Test your typing speed in WPM and accuracy with real-time feedback',                  category:'utility', icon:'⌨️', trending:true,  premium:false, enabled:true, tags:['typing','speed','wpm','accuracy'] },
];

const CATEGORIES = {
  text:    { name:'Text Tools',    icon:'📝', color:'#6366f1' },
  media:   { name:'Media Tools',   icon:'🎬', color:'#f43f5e' },
  utility: { name:'Utility Tools', icon:'⚙️', color:'#10b981' }
};

let _disabledTools = new Set();
function setDisabledTools(ids) { _disabledTools = new Set(ids); }
function isEnabled(id) { return !_disabledTools.has(id); }

const getToolById   = (id)  => TOOLS.find(t => t.id === id);
const getTrending   = ()    => TOOLS.filter(t => t.trending && isEnabled(t.id));
const getByCategory = (cat) => TOOLS.filter(t => t.category === cat && isEnabled(t.id));
const getAllTools    = ()    => TOOLS.map(t => ({ ...t, enabled: isEnabled(t.id) }));
const searchTools   = (q)   => {
  const ql = q.toLowerCase();
  return TOOLS.filter(t =>
    isEnabled(t.id) &&
    (t.name.toLowerCase().includes(ql) ||
     t.description.toLowerCase().includes(ql) ||
     t.tags.some(tag => tag.includes(ql)))
  );
};

module.exports = { TOOLS, CATEGORIES, getToolById, getTrending, getByCategory, getAllTools, searchTools, setDisabledTools, isEnabled };
