/**
 * ToolHub AI — AI Content Detector
 * File: routes/api/text/aiDetector.js
 *
 * Analyses text using statistical and linguistic heuristics to estimate
 * the likelihood it was generated by an AI language model.
 * Fully deterministic — zero external API calls.
 *
 * Detection Vectors:
 *   V1  — Sentence Length Uniformity (Burstiness Score)
 *   V2  — AI Filler & Boilerplate Phrase Density
 *   V3  — Formal Vocabulary Saturation
 *   V4  — Passive Voice Ratio
 *   V5  — Sentence Opener Monotony
 *   V6  — Transition Word Overuse
 *   V7  — Hedge Language Density
 *   V8  — Adverb Filler Density
 *   V9  — Average Word Length Elevation
 *   V10 — Type-Token Ratio (Lexical Diversity)
 *   V11 — Subordinate Clause Density
 *   V12 — List / Enumeration Pattern Detection
 *   V13 — Structural Formula Patterns
 *   V14 — Paragraph Length Uniformity
 *   V15 — Contraction Absence (AI rarely uses contractions)
 */

'use strict';

// ── V2: AI Filler & Boilerplate Phrases ──────────────────────────────────────

const AI_BOILERPLATE = [
  /\bit is important to note\b/gi,
  /\bit should be noted\b/gi,
  /\bit is worth noting\b/gi,
  /\bit is worth mentioning\b/gi,
  /\bplease note that\b/gi,
  /\bin conclusion\b/gi,
  /\bin summary\b/gi,
  /\bto summarize\b/gi,
  /\bto conclude\b/gi,
  /\bin this article\b/gi,
  /\bin this essay\b/gi,
  /\bin this post\b/gi,
  /\bin this blog\b/gi,
  /\bthis article will\b/gi,
  /\bthis essay will\b/gi,
  /\bwe will explore\b/gi,
  /\bwe will discuss\b/gi,
  /\blet's explore\b/gi,
  /\blet us explore\b/gi,
  /\blet's delve\b/gi,
  /\blet us delve\b/gi,
  /\bdelving into\b/gi,
  /\bshed light on\b/gi,
  /\bwithout further ado\b/gi,
  /\bas an ai\b/gi,
  /\bas a language model\b/gi,
  /\bcertainly[,!]\s/gi,
  /\babsolutely[,!]\s/gi,
  /\bof course[,!]\s/gi,
  /\bgreat question\b/gi,
  /\bexcellent question\b/gi,
  /\bwonderful question\b/gi,
  /\bhope (this|that) helps\b/gi,
  /\bfeel free to ask\b/gi,
  /\bdon't hesitate to\b/gi,
  /\bis there anything else\b/gi,
  /\bfirst and foremost\b/gi,
  /\bneedless to say\b/gi,
  /\bwithout a doubt\b/gi,
  /\bit is widely (known|accepted|believed|recognized)\b/gi,
  /\bone of the most (important|significant|crucial|key)\b/gi,
  /\bplays? a (crucial|vital|key|important|significant|pivotal) role\b/gi,
  /\ba comprehensive (guide|overview|look|analysis|understanding)\b/gi,
  /\bkey (aspects?|points?|factors?|elements?|components?|takeaways?)\b/gi,
  /\bin today's (world|society|digital age|fast-paced world|landscape)\b/gi,
  /\bin the (modern|digital|contemporary) era\b/gi,
  /\bthe (importance|significance|impact) of\b/gi,
  /\bboth.*and.*are (important|significant|crucial)\b/gi,
  /\bit is (essential|crucial|important|necessary) to\b/gi,
  /\bone must (consider|understand|recognize|note)\b/gi,
];

// ── V3: Formal / AI-preferred Vocabulary ─────────────────────────────────────

const FORMAL_VOCAB = [
  /\butiliz[ei]/gi, /\bfacilitat/gi, /\bleverage[ds]?\b/gi,
  /\boptimal\b/gi, /\boptimiz/gi, /\bmaximiz/gi, /\bminimiz/gi,
  /\benhance[ds]?\b/gi, /\benhancing\b/gi, /\benhancement/gi,
  /\bimplementation\b/gi, /\bimplement\b/gi,
  /\bcomprehensive\b/gi, /\brobust\b/gi, /\bscalable\b/gi,
  /\bsynergy\b/gi, /\bsynergies\b/gi,
  /\bparadigm\b/gi, /\bframework\b/gi,
  /\bhenceforth\b/gi, /\bheretofore\b/gi,
  /\bafforementioned\b/gi, /\baforementioned\b/gi,
  /\bnevertheless\b/gi, /\bnotwithstanding\b/gi,
  /\bsubsequently\b/gi, /\bprecedent\b/gi,
  /\bcommensurate\b/gi, /\binherent(?:ly)?\b/gi,
  /\bpervasive\b/gi, /\bprevalent\b/gi,
  /\bindispensable\b/gi, /\bpivotal\b/gi,
  /\btransformative\b/gi, /\bgroundbreaking\b/gi,
  /\bcutting-edge\b/gi, /\bstate-of-the-art\b/gi,
  /\binnovative\b/gi, /\bstakeholders?\b/gi,
  /\bactionable\b/gi, /\binsightful\b/gi, /\bimpactful\b/gi,
  /\bhighly effective\b/gi, /\bextremely important\b/gi,
  /\bcritical(?:ly)?\b/gi, /\bcrucial(?:ly)?\b/gi,
  /\bfundamentally\b/gi, /\bprimarily\b/gi,
  /\bsignificantly\b/gi, /\bsubstantially\b/gi,
  /\bspecifically\b/gi, /\bparticularly\b/gi,
];

// ── V4: Passive Voice Markers ─────────────────────────────────────────────────

const PASSIVE_PATTERNS = [
  /\b(is|are|was|were|been|be|being)\s+(being\s+)?[a-z]+(?:ed|en|t)\b/gi,
  /\bhas\s+been\s+[a-z]+(?:ed|en|t)\b/gi,
  /\bhave\s+been\s+[a-z]+(?:ed|en|t)\b/gi,
  /\bhad\s+been\s+[a-z]+(?:ed|en|t)\b/gi,
  /\bwill\s+be\s+[a-z]+(?:ed|en|t)\b/gi,
  /\bcan\s+be\s+[a-z]+(?:ed|en|t)\b/gi,
  /\bshould\s+be\s+[a-z]+(?:ed|en|t)\b/gi,
  /\bmay\s+be\s+[a-z]+(?:ed|en|t)\b/gi,
];

// ── V6: Transition Word Overuse ───────────────────────────────────────────────

const HEAVY_TRANSITIONS = [
  /\bfurthermore\b/gi,
  /\badditionally\b/gi,
  /\bmoreover\b/gi,
  /\bconsequently\b/gi,
  /\bnevertheless\b/gi,
  /\bhenceforth\b/gi,
  /\btherefore\b/gi,
  /\bthus\b/gi,
  /\bhence\b/gi,
  /\bin addition\b/gi,
  /\bbesides\b/gi,
  /\bon the other hand\b/gi,
  /\bin contrast\b/gi,
  /\bhowever\b/gi,
  /\bnonetheless\b/gi,
];

// ── V7: Hedge Language ────────────────────────────────────────────────────────

const HEDGE_PHRASES = [
  /\bit is worth noting\b/gi,
  /\bit should be mentioned\b/gi,
  /\bone might argue\b/gi,
  /\bsome may suggest\b/gi,
  /\bsome experts believe\b/gi,
  /\bit can be argued\b/gi,
  /\bsome would say\b/gi,
  /\bto some extent\b/gi,
  /\bin some cases\b/gi,
  /\bin many (cases|instances|situations|contexts)\b/gi,
  /\bcan (often|sometimes|generally|typically) be\b/gi,
  /\btends? to be\b/gi,
  /\bmight be (considered|seen as|viewed as)\b/gi,
];

// ── V8: AI Adverb Fillers ─────────────────────────────────────────────────────

const ADVERB_FILLERS = [
  /\bclearly\b/gi, /\bundoubtedly\b/gi, /\bunquestionably\b/gi,
  /\bdefinitely\b/gi, /\bcertainly\b/gi, /\babsolutely\b/gi,
  /\bapparently\b/gi, /\bpresumably\b/gi, /\bobviously\b/gi,
  /\binterestingly\b/gi, /\bnotably\b/gi, /\bimportantly\b/gi,
  /\bessentially\b/gi, /\bfundamentally\b/gi, /\bultimately\b/gi,
];

// ── V13: Structural Formula Detectors ────────────────────────────────────────

const STRUCTURAL_FORMULAS = [
  // Concluding sentence patterns
  /\bin (conclusion|summary|closing)[,:]?\s/gi,
  /overall[,:]?\s+(it|this|these|we|the)/gi,
  /to (summarize|conclude|recap|wrap up)[,:]?\s/gi,
  // Intro patterns
  /^(this article|this post|this guide|this essay|this piece) (will|aims to|explores|discusses|examines)/gim,
  /^(in this article|in this post|in this guide|in this tutorial)[,:]?\s/gim,
  // Body patterns
  /^(first(ly)?|second(ly)?|third(ly)?)[,:]?\s/gim,
  /^(last(ly)?|finally|in addition)[,:]?\s/gim,
  // Question-answer pattern
  /\b(so|now)[,]?\s+what (is|are|does|can|should)\b/gi,
];

// ── V15: Contraction Absence Detection ───────────────────────────────────────

const CONTRACTIONS = [
  /\bcan't\b/gi, /\bwon't\b/gi, /\bdon't\b/gi, /\bdoesn't\b/gi,
  /\bdidn't\b/gi, /\bwouldn't\b/gi, /\bcouldn't\b/gi, /\bshouldn't\b/gi,
  /\bisn't\b/gi, /\baren't\b/gi, /\bwasn't\b/gi, /\bweren't\b/gi,
  /\bI'm\b/g, /\bI've\b/g, /\bI'll\b/g, /\bI'd\b/g,
  /\byou're\b/gi, /\byou've\b/gi, /\byou'll\b/gi, /\byou'd\b/gi,
  /\bhe's\b/gi, /\bshe's\b/gi, /\bit's\b/gi, /\bwe're\b/gi,
  /\bthey're\b/gi, /\bthey've\b/gi, /\bthat's\b/gi, /\bthere's\b/gi,
  /\bhere's\b/gi, /\bwhat's\b/gi, /\bwho's\b/gi, /\blet's\b/gi,
];

// ── Helper: Sentence Segmentation ────────────────────────────────────────────

function splitSentences(text) {
  const abbrev = text.replace(/\b(Mr|Mrs|Ms|Dr|Prof|Sr|Jr|vs|etc|Inc|Ltd|Jan|Feb|Mar|Apr|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\./gi, m => m.replace('.', '⟨DOT⟩'));
  const parts = abbrev.match(/[^.!?]+[.!?]+["']?\s*/g) || [text];
  return parts.map(s => s.replace(/⟨DOT⟩/g, '.').trim()).filter(s => s.length > 5);
}

function countWords(text) {
  return (text.match(/\b[a-z]+\b/gi) || []).length;
}

function countMatches(text, patterns) {
  if (!Array.isArray(patterns)) patterns = [patterns];
  return patterns.reduce((total, pat) => {
    const re = new RegExp(pat.source, pat.flags.replace(/g/,'') + 'g');
    const matches = text.match(re) || [];
    return total + matches.length;
  }, 0);
}

// ── V1: Burstiness (Sentence Length Uniformity) ───────────────────────────────

function scoreBurstiness(sentences) {
  if (sentences.length < 3) return 0;
  const lengths = sentences.map(s => s.split(/\s+/).length);
  const mean = lengths.reduce((a, b) => a + b, 0) / lengths.length;
  const variance = lengths.reduce((sum, l) => sum + Math.pow(l - mean, 2), 0) / lengths.length;
  const stdDev = Math.sqrt(variance);
  const cv = mean > 0 ? stdDev / mean : 0; // Coefficient of variation
  // Humans: high CV (varied lengths). AI: low CV (uniform)
  // CV < 0.3 → very uniform (AI signal)
  // CV > 0.6 → very varied (human signal)
  if (cv < 0.2) return 90;
  if (cv < 0.3) return 75;
  if (cv < 0.4) return 55;
  if (cv < 0.5) return 35;
  if (cv < 0.6) return 20;
  return 5;
}

// ── V5: Sentence Opener Monotony ─────────────────────────────────────────────

function scoreSentenceOpenerMonotony(sentences) {
  if (sentences.length < 4) return 0;
  const openers = sentences.map(s => {
    const first = (s.match(/^(?:The|It|This|That|These|Those|There|In|On|By|For|To|As|With)\b/i) || [''])[0].toLowerCase();
    return first || 'other';
  });
  const counts = {};
  for (const o of openers) counts[o] = (counts[o] || 0) + 1;
  const maxRepeat = Math.max(...Object.values(counts));
  const monotonyRatio = maxRepeat / sentences.length;
  if (monotonyRatio > 0.6) return 85;
  if (monotonyRatio > 0.4) return 65;
  if (monotonyRatio > 0.25) return 40;
  if (monotonyRatio > 0.15) return 20;
  return 5;
}

// ── V10: Type-Token Ratio ─────────────────────────────────────────────────────

function scoreTTR(text) {
  const words = (text.toLowerCase().match(/\b[a-z]{3,}\b/g) || []);
  if (words.length < 20) return 0;
  const unique = new Set(words).size;
  const ttr = unique / words.length;
  // Human writing: TTR varies but tends higher. AI: consistent low TTR for long text.
  // For texts > 200 words, TTR typically: human 0.4-0.6, AI 0.3-0.45
  const adjustedTTR = words.length > 200 ? ttr * (1 + (words.length - 200) / 1000) : ttr;
  if (adjustedTTR < 0.35) return 75;
  if (adjustedTTR < 0.45) return 50;
  if (adjustedTTR < 0.55) return 30;
  if (adjustedTTR < 0.65) return 15;
  return 5;
}

// ── V9: Average Word Length ───────────────────────────────────────────────────

function scoreWordLength(text) {
  const words = (text.match(/\b[a-z]{2,}\b/gi) || []);
  if (words.length === 0) return 0;
  const avgLen = words.reduce((sum, w) => sum + w.length, 0) / words.length;
  // Human writing: avg word length 4.0–5.5. AI: 5.5–7.0+
  if (avgLen > 6.5) return 80;
  if (avgLen > 6.0) return 65;
  if (avgLen > 5.5) return 45;
  if (avgLen > 5.0) return 25;
  if (avgLen > 4.5) return 10;
  return 0;
}

// ── V15: Contraction Absence ─────────────────────────────────────────────────

function scoreContractionAbsence(text, wordCount) {
  if (wordCount < 50) return 0;
  const contractionCount = CONTRACTIONS.reduce((sum, pat) => {
    const re = new RegExp(pat.source, pat.flags.replace(/g/,'') + 'g');
    return sum + (text.match(re) || []).length;
  }, 0);
  const rate = contractionCount / (wordCount / 100); // per 100 words
  // AI rarely uses contractions; humans use them frequently in natural writing
  // Rate > 3 per 100 words → human. Rate < 0.5 → AI signal.
  if (rate === 0 && wordCount > 100) return 70;
  if (rate < 0.5) return 55;
  if (rate < 1.5) return 35;
  if (rate < 3.0) return 15;
  return 0;
}

// ── V11: Subordinate Clause Density ──────────────────────────────────────────

const SUBORDINATE_MARKERS = /\b(which|that|who|whom|whose|because|although|whereas|while|since|unless|whether|if|even though|as long as|provided that|given that)\b/gi;

function scoreSubordinateDensity(text, wordCount) {
  if (wordCount < 20) return 0;
  const count = (text.match(SUBORDINATE_MARKERS) || []).length;
  const rate = count / (wordCount / 100);
  // AI tends to overuse subordinate clauses for elaboration
  if (rate > 12) return 70;
  if (rate > 8) return 50;
  if (rate > 5) return 30;
  return 0;
}

// ── V12: List / Enumeration Patterns ─────────────────────────────────────────

function scoreListPatterns(text, sentences) {
  const bulletLines = (text.match(/^[\s]*[-•*]\s/gm) || []).length;
  const numberedLines = (text.match(/^[\s]*\d+[.)]\s/gm) || []).length;
  const enumPhrases = countMatches(text, [
    /\bfirst(?:ly)?,\s/gi,
    /\bsecond(?:ly)?,\s/gi,
    /\bthird(?:ly)?,\s/gi,
    /\bfourth(?:ly)?,\s/gi,
    /\bfinally,\s/gi,
    /\blast(?:ly)?,\s/gi,
  ]);
  const total = bulletLines + numberedLines + enumPhrases;
  const ratio = sentences.length > 0 ? total / sentences.length : 0;
  if (ratio > 0.8) return 80;
  if (ratio > 0.4) return 60;
  if (ratio > 0.2) return 35;
  if (total > 3) return 20;
  return 0;
}

// ── Main Scorer ───────────────────────────────────────────────────────────────

function detectAI(text) {
  if (!text || text.trim().length === 0) throw new Error('Please enter text to analyze.');
  if (text.trim().split(/\s+/).length < 20) throw new Error('Please enter at least 20 words for a reliable analysis.');
  if (text.length > 15000) throw new Error('Text too long. Maximum 15,000 characters.');

  const sentences = splitSentences(text);
  const wordCount = countWords(text);

  // ── Calculate each vector ──────────────────────────────────────────────────
  const v1 = scoreBurstiness(sentences);

  const fillerCount = countMatches(text, AI_BOILERPLATE);
  const fillerDensity = fillerCount / (wordCount / 100);
  const v2 = Math.min(100, fillerDensity > 3 ? 90 : fillerDensity > 1.5 ? 70 : fillerDensity > 0.5 ? 45 : fillerDensity > 0 ? 20 : 0);

  const formalCount = countMatches(text, FORMAL_VOCAB);
  const formalDensity = formalCount / (wordCount / 100);
  const v3 = Math.min(100, formalDensity > 10 ? 85 : formalDensity > 6 ? 65 : formalDensity > 3 ? 40 : formalDensity > 1 ? 20 : 5);

  const passiveCount = countMatches(text, PASSIVE_PATTERNS);
  const passiveRate = passiveCount / sentences.length;
  const v4 = Math.min(100, passiveRate > 0.6 ? 85 : passiveRate > 0.4 ? 65 : passiveRate > 0.2 ? 40 : passiveRate > 0.1 ? 20 : 5);

  const v5 = scoreSentenceOpenerMonotony(sentences);

  const transitionCount = countMatches(text, HEAVY_TRANSITIONS);
  const transitionDensity = transitionCount / (wordCount / 100);
  const v6 = Math.min(100, transitionDensity > 3 ? 80 : transitionDensity > 1.5 ? 60 : transitionDensity > 0.5 ? 35 : 5);

  const hedgeCount = countMatches(text, HEDGE_PHRASES);
  const hedgeDensity = hedgeCount / (wordCount / 100);
  const v7 = Math.min(100, hedgeDensity > 2 ? 75 : hedgeDensity > 1 ? 55 : hedgeDensity > 0.3 ? 30 : 5);

  const adverbCount = countMatches(text, ADVERB_FILLERS);
  const adverbDensity = adverbCount / (wordCount / 100);
  const v8 = Math.min(100, adverbDensity > 4 ? 80 : adverbDensity > 2 ? 60 : adverbDensity > 0.5 ? 30 : 5);

  const v9 = scoreWordLength(text);
  const v10 = scoreTTR(text);

  const v11 = scoreSubordinateDensity(text, wordCount);
  const v12 = scoreListPatterns(text, sentences);

  const structCount = countMatches(text, STRUCTURAL_FORMULAS);
  const v13 = Math.min(100, structCount > 3 ? 85 : structCount > 1 ? 55 : structCount > 0 ? 25 : 0);

  const v14 = (() => {
    const paragraphs = text.split(/\n\n+/).filter(p => p.trim().length > 20);
    if (paragraphs.length < 3) return 0;
    const pLengths = paragraphs.map(p => p.split(/\s+/).length);
    const mean = pLengths.reduce((a, b) => a + b, 0) / pLengths.length;
    const std = Math.sqrt(pLengths.reduce((s, l) => s + Math.pow(l - mean, 2), 0) / pLengths.length);
    const cv = mean > 0 ? std / mean : 1;
    return cv < 0.15 ? 75 : cv < 0.25 ? 55 : cv < 0.4 ? 30 : 5;
  })();

  const v15 = scoreContractionAbsence(text, wordCount);

  // ── Weighted score ─────────────────────────────────────────────────────────
  const vectors = [
    { name: 'Sentence Length Uniformity',   score: v1,  weight: 2.2, label: 'Burstiness' },
    { name: 'AI Boilerplate Phrases',        score: v2,  weight: 3.0, label: 'Boilerplate' },
    { name: 'Formal Vocabulary Density',     score: v3,  weight: 2.2, label: 'Formal Vocab' },
    { name: 'Passive Voice Ratio',           score: v4,  weight: 1.2, label: 'Passive Voice' },
    { name: 'Sentence Opener Repetition',    score: v5,  weight: 1.6, label: 'Opener Variety' },
    { name: 'Transition Word Overuse',       score: v6,  weight: 1.5, label: 'Transitions' },
    { name: 'Hedging Language Density',      score: v7,  weight: 1.3, label: 'Hedge Language' },
    { name: 'Adverb Filler Density',         score: v8,  weight: 1.2, label: 'Adverb Fillers' },
    { name: 'Word Length Elevation',         score: v9,  weight: 1.2, label: 'Word Length' },
    { name: 'Lexical Diversity (TTR)',        score: v10, weight: 1.0, label: 'Vocabulary' },
    { name: 'Clause Complexity',             score: v11, weight: 0.8, label: 'Clauses' },
    { name: 'List / Enumeration Patterns',   score: v12, weight: 1.0, label: 'List Patterns' },
    { name: 'Structural Formula Patterns',   score: v13, weight: 1.8, label: 'Structure' },
    { name: 'Paragraph Length Uniformity',   score: v14, weight: 1.2, label: 'Paragraphs' },
    { name: 'Contraction Absence',           score: v15, weight: 1.5, label: 'Contractions' },
  ];

  const totalWeight = vectors.reduce((s, v) => s + v.weight, 0);
  const weightedSum  = vectors.reduce((s, v) => s + v.score * v.weight, 0);
  let rawScore = Math.round(weightedSum / totalWeight);

  // Boost: when top 3 signals are all strong (>= 70), amplify the result
  const highSignals = vectors.filter(v => v.score >= 70).length;
  if (highSignals >= 4) rawScore = Math.min(99, rawScore + 15);
  else if (highSignals >= 3) rawScore = Math.min(99, rawScore + 10);
  else if (highSignals >= 2) rawScore = Math.min(99, rawScore + 5);

  const aiScore = Math.min(99, Math.max(1, rawScore));

  // ── Verdict ────────────────────────────────────────────────────────────────
  let verdict, verdictIcon, verdictColor;
  if (aiScore >= 75) {
    verdict = 'Very likely AI-generated'; verdictIcon = '🤖'; verdictColor = '#ef4444';
  } else if (aiScore >= 55) {
    verdict = 'Possibly AI-generated';    verdictIcon = '⚠️'; verdictColor = '#f97316';
  } else if (aiScore >= 35) {
    verdict = 'Mixed — human + AI likely'; verdictIcon = '🔶'; verdictColor = '#eab308';
  } else if (aiScore >= 20) {
    verdict = 'Mostly human-written';     verdictIcon = '👤'; verdictColor = '#22c55e';
  } else {
    verdict = 'Very likely human-written'; verdictIcon = '✅'; verdictColor = '#16a34a';
  }

  // Top signals
  const topSignals = [...vectors]
    .sort((a, b) => (b.score * b.weight) - (a.score * a.weight))
    .slice(0, 5)
    .filter(v => v.score > 15)
    .map(v => ({ name: v.name, score: v.score, label: v.label }));

  // Stats
  const avgSentenceWords = sentences.length ? Math.round(wordCount / sentences.length) : 0;
  const avgWordLen = wordCount > 0
    ? (text.match(/\b[a-z]{2,}\b/gi) || []).reduce((s, w) => s + w.length, 0) / wordCount
    : 0;

  return {
    aiScore,
    humanScore: 100 - aiScore,
    verdict,
    verdictIcon,
    verdictColor,
    vectors: vectors.map(v => ({ name: v.name, label: v.label, score: v.score })),
    topSignals,
    stats: {
      wordCount,
      sentenceCount: sentences.length,
      avgSentenceWords,
      avgWordLength: parseFloat(avgWordLen.toFixed(1)),
      formalWordCount: formalCount,
      boilerphraseCount: fillerCount,
      passiveSentences: passiveCount,
    },
  };
}

function run(input) {
  const text = (input || '').trim();
  if (!text) return { error: 'Please enter some text to analyze.' };
  try {
    return detectAI(text);
  } catch (err) {
    return { error: err.message || 'Analysis failed. Please try again.' };
  }
}

module.exports = { run, detectAI };
